(function(){
const API='https://moe-ai-production.up.railway.app',STORAGE='moeAcademyV3',LEGACY='moeAcademyV2';
const token=()=>sessionStorage.getItem('moeAgentSession')||'';
let lastSignature='',syncing=false;
async function req(path,opts={}){const t=token(),r=await fetch(API+path,{...opts,headers:{'Content-Type':'application/json',...(t?{Authorization:'Bearer '+t}:{}),...(opts.headers||{})}}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.detail||j.error||('HTTP '+r.status));return j}
function read(){try{const current=JSON.parse(localStorage.getItem(STORAGE)||'null');if(current)return current;const legacy=JSON.parse(localStorage.getItem(LEGACY)||'null');if(legacy){localStorage.setItem(STORAGE,JSON.stringify(legacy));return legacy}}catch{}return{completed:{},scores:{}}}
function write(s){localStorage.setItem(STORAGE,JSON.stringify(s))}
function signature(s){return JSON.stringify(Object.entries(s.scores||{}).sort())}
function msg(text,bad=false){const e=document.getElementById('academyXpMsg');if(e){e.textContent=text;e.style.color=bad?'#ff8d9b':'#8190ad'}}
function addPanel(){const d=document.querySelector('.dashboard .container');if(!d||document.getElementById('academyXpPanel'))return;const p=document.createElement('div');p.id='academyXpPanel';p.className='card moer-panel-purple';p.style.cssText='padding:18px;margin-top:14px';p.innerHTML='<div class="section-label">ACADEMY → PASSPORT</div><h3 style="margin:8px 0">Learning progress follows your wallet</h3><p style="color:var(--muted);margin:0 0 12px">Passed modules sync automatically to your Moerverse Passport. A pass earns 10 XP once; a 90%+ score earns 15 XP once. Returning with the same holder wallet restores server-synced completed modules.</p><button class="button secondary" id="academyXpSync">SYNC NOW</button><span id="academyXpMsg" style="margin-left:10px;font-size:11px;color:#8190ad"></span>';d.appendChild(p);document.getElementById('academyXpSync').onclick=()=>sync(true)}
async function restore(){if(!token())return false;try{const x=await req('/v1/ecosystem/academy/progress'),remote=x.progress||{},scores=remote.scores||{};if(!Object.keys(scores).length)return false;const s=read();s.completed=s.completed||{};s.scores=s.scores||{};let changed=false;for(const [moduleId,scoreRaw] of Object.entries(scores)){const score=Number(scoreRaw||0);if(score<70)continue;if(Number(s.scores[moduleId]||0)<score){s.scores[moduleId]=score;changed=true}if(!s.completed[moduleId]){s.completed[moduleId]=true;changed=true}}if(changed){write(s);msg(`Restored ${Object.keys(scores).length} completed module${Object.keys(scores).length===1?'':'s'} from your Passport.`);setTimeout(()=>location.reload(),350)}return changed}catch(e){if(!/404|not found/i.test(String(e.message)))console.warn('Academy Passport restore unavailable:',e);return false}}
async function sync(manual=false){if(syncing)return;if(!token()){if(manual)msg('Authenticate your Passport first. Your local lesson progress is unchanged.',true);return}const s=read(),scores=s.scores||{},sig=signature(s);if(!manual&&sig===lastSignature)return;syncing=true;let total=0,claimed=0,failed=0;for(const [moduleId,scoreRaw] of Object.entries(scores)){const score=Number(scoreRaw||0);if(score<70)continue;total++;try{const x=await req('/v1/ecosystem/academy/claim',{method:'POST',body:JSON.stringify({module_id:moduleId,score})});if(x.xp_awarded)claimed+=Number(x.xp_awarded||0)}catch{failed++}}lastSignature=sig;syncing=false;if(manual||claimed||failed)msg(total?`Passport synced: ${total} passed module${total===1?'':'s'}${claimed?' • +'+claimed+' XP':''}${failed?' • '+failed+' pending retry':''}`:'No passed scored modules yet.',failed>0&&failed===total)}
async function boot(){addPanel();if(token()){const restored=await restore();if(!restored){lastSignature='';await sync(false)}}setInterval(()=>sync(false),4000)}
document.addEventListener('DOMContentLoaded',()=>{if(location.pathname.startsWith('/academy/'))setTimeout(boot,500)});
window.addEventListener('basedmoer:wallet',()=>setTimeout(async()=>{lastSignature='';await restore();sync(false)},250));
})();