(function(){
  const API='https://moe-ai-production.up.railway.app/v1/agent';
  const EXEC='https://moe-ai-production.up.railway.app/v1/execution';
  const tokenKey='moeAgentSession';
  const $=id=>document.getElementById(id);
  const money=v=>Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:4});
  function wallet(){return (sessionStorage.getItem('basedMoerWallet')||'').toLowerCase()}
  function walletSource(){return sessionStorage.getItem('basedMoerWalletSource')||''}
  function token(){return sessionStorage.getItem(tokenKey)||''}
  function headers(){const t=token();return t?{'Authorization':'Bearer '+t,'Content-Type':'application/json'}:{'Content-Type':'application/json'}}
  async function json(url,opts={}){const r=await fetch(url,{...opts,headers:{...headers(),...(opts.headers||{})}});const x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.detail||x.error||('HTTP '+r.status));return x}
  function state(text,bad=false){const e=$('agentMessage');if(e){e.textContent=text;e.style.color=bad?'#ff8d9b':'#8190ad'}}
  function messageHex(text){return '0x'+Array.from(new TextEncoder().encode(String(text||'')),b=>b.toString(16).padStart(2,'0')).join('')}
  function sameAccount(a,b){return String(a||'').toLowerCase()===String(b||'').toLowerCase()}
  async function baseAccountProvider(){if(!window.MoerBaseAccount?.provider){await import('/base-account.js')}const provider=window.MoerBaseAccount?.provider;if(!provider?.request)throw new Error('Base Account provider is unavailable.');return provider}
  async function providerAccount(provider,promptIfMissing=false){let accounts=await provider.request({method:'eth_accounts'}).catch(()=>[]);if(!accounts?.[0]&&promptIfMissing)accounts=await provider.request({method:'eth_requestAccounts'});return String(accounts?.[0]||'').toLowerCase()}
  async function signingProvider(expectedWallet){const source=walletSource();if(source==='base_account'){const provider=await baseAccountProvider();const connected=await providerAccount(provider,true);if(!sameAccount(connected,expectedWallet))throw new Error('Base Account does not match the holder wallet. Authentication was cancelled.');return {provider,source:'base_account'}}if(source==='injected_wallet'){if(!window.ethereum?.request)throw new Error('The injected wallet used for holder access is no longer available.');const connected=await providerAccount(window.ethereum,false);if(!sameAccount(connected,expectedWallet))throw new Error('Injected wallet does not match the holder wallet. Authentication was cancelled.');return {provider:window.ethereum,source:'injected_wallet'}}try{const provider=await baseAccountProvider();const connected=await providerAccount(provider,false);if(sameAccount(connected,expectedWallet))return {provider,source:'base_account'}}catch{}if(window.ethereum?.request){const connected=await providerAccount(window.ethereum,false);if(sameAccount(connected,expectedWallet))return {provider:window.ethereum,source:'injected_wallet'}}throw new Error('Reconnect your holder wallet before authenticating Moe Agent.')}
  async function signAgentChallenge(message,expectedWallet){const signing=await signingProvider(expectedWallet);const data=signing.source==='base_account'?messageHex(message):message;const signature=await signing.provider.request({method:'personal_sign',params:[data,expectedWallet]});if(!/^0x[0-9a-f]+$/i.test(String(signature||'')))throw new Error('Wallet returned an invalid signature.');return {signature,source:signing.source}}
  function ensureExecutionPanel(){if($('baseExecPanel'))return;const panel=$('agentPanel');if(!panel)return;const wrap=document.createElement('section');wrap.id='baseExecPanel';wrap.style.cssText='margin-top:18px;padding:16px;border:1px solid #263149;border-radius:13px;background:#080d15';wrap.innerHTML=`<div style="font-size:10px;font-weight:900;color:#71809e;margin-bottom:8px">BASE-NATIVE EXECUTION READINESS</div><div id="baseExecStatus" style="font-size:13px;color:#9aa8c4;line-height:1.6">Checking Base shadow routes...</div><div style="display:flex;gap:10px;flex-wrap:wrap;margin-top:12px"><button id="baseExecCheck" class="button secondary" type="button">CHECK BASE ROUTES</button><button id="basePermissionPlan" class="button secondary" type="button">REQUEST $10 BASE PERMISSION</button></div><div id="basePermissionStatus" style="margin-top:10px;font-size:12px;color:#7f8da9;line-height:1.6">Base Account Spend Permission support is wired for bounded USDC permissions, status checks and user revocation. The Moe spender and live execution remain separately locked behind security gates.</div>`;panel.appendChild(wrap);$('baseExecCheck')?.addEventListener('click',checkExecutionHealth);$('basePermissionPlan')?.addEventListener('click',preparePermission)}
  async function checkExecutionHealth(){const e=$('baseExecStatus');if(e)e.textContent='Checking Base mainnet routes...';try{const x=await json(EXEC+'/health');const eth=x.checks?.ETHUSDT,btx=x.checks?.BTCUSDT;const native=x.base_native?.ok?'FLASHBLOCKS READY':'FLASHBLOCKS CONTEXT NOT READY';if(e)e.textContent=`Base ${x.chain_id||8453}: ETH route ${eth?.ok?'OK':'NOT READY'} · BTC/cbBTC route ${btx?.ok?'OK':'NOT READY'} · ${native} · mode ${x.mode||'SHADOW'}.`}catch(err){if(e)e.textContent='Base execution health unavailable: '+err.message}}
  async function preparePermission(){const e=$('basePermissionStatus');if(e)e.textContent='Building a server-bounded $10 USDC permission plan...';try{const x=await json(EXEC+'/permission-plan',{method:'POST',body:JSON.stringify({allowance_usd:10,period_days:30})});if(!x.ready){if(e)e.textContent='Live permission remains locked: '+(x.message||x.reason||'spender not deployed');return}if(x.execution_enabled!==false)throw new Error('Permission endpoint did not report execution as locked. Refusing to continue.');if(!window.MoerBaseAccount?.signPreparedPermission){await import('/base-account.js')}if(!window.MoerBaseAccount?.signPreparedPermission){if(e)e.textContent='Base Account module is not available. No permission was requested.';return}if(e)e.textContent='Bounded plan verified. Opening Base Account for your review...';await window.MoerBaseAccount.signPreparedPermission(x)}catch(err){if(e){e.textContent='Permission request failed safely: '+err.message;e.style.color='#ff8d9b'}}}
  function renderAccount(a,positions=[]){if(!a)return;$('agentMode').textContent=a.mode||'PAPER';$('agentState').textContent=a.enabled?'RUNNING':'STOPPED';$('agentCash').textContent='$'+money(a.paper_cash_balance);$('agentPnl').textContent=(Number(a.realized_pnl||0)>=0?'+':'')+'$'+money(a.realized_pnl);$('agentOpen').textContent=positions.filter(p=>p.status==='OPEN').length;$('paperStart').value=Number(a.paper_start_balance||10);$('maxAllocation').value=Number(a.max_total_allocation||10);$('maxPosition').value=Number(a.max_position_size||2);$('maxOpen').value=Number(a.max_open_positions||2);$('maxDailyLoss').value=Number(a.max_daily_loss||2);$('minConfidence').value=Number(a.min_signal_confidence||80);$('agentStart').disabled=!!a.enabled;$('agentStop').disabled=!a.enabled;$('agentSave').disabled=!!a.enabled;const area=$('agentPositions');if(area){area.innerHTML=positions.length?positions.slice(0,20).map(p=>`<div class="agent-pos"><strong>${p.symbol}</strong><span>${p.status}</span><span>$${money(p.notional)}</span><span>${Number(p.pnl_usd||0)>=0?'+':''}$${money(p.pnl_usd)}</span></div>`).join(''):'<div class="agent-empty">No paper positions yet.</div>'}}
  async function load(){if(!wallet()){state('Connect your holder wallet first.',true);return}if(!token()){state('Authenticate Moe Agent with a wallet signature. This proves wallet ownership only and does not authorize a transaction.');$('agentAuth').hidden=false;return}try{const x=await json(API+'/me');$('agentAuth').hidden=true;$('agentPanel').hidden=false;ensureExecutionPanel();renderAccount(x.account,x.positions||[]);state('Moe Agent shadow engine connected. Live fund execution remains locked.');checkExecutionHealth()}catch(e){sessionStorage.removeItem(tokenKey);$('agentAuth').hidden=false;$('agentPanel').hidden=true;state(e.message,true)}}
  async function authenticate(){const w=wallet();if(!w){state('Connect your holder wallet first.',true);return}try{state('Creating secure holder challenge...');const c=await json(API+'/auth/challenge',{method:'POST',body:JSON.stringify({wallet_address:w})});if(!sameAccount(c.wallet_address,w))throw new Error('Server challenge wallet does not match the connected holder wallet.');state(walletSource()==='base_account'?'Opening Base Account for login signature...':'Opening wallet for login signature...');const signed=await signAgentChallenge(c.message,w);const v=await json(API+'/auth/verify',{method:'POST',body:JSON.stringify({wallet_address:w,signature:signed.signature})});sessionStorage.setItem(tokenKey,v.session_token);state(`Authenticated with ${signed.source==='base_account'?'Base Account':'wallet'} signature. No transaction permission was granted.`);await load()}catch(e){state(e.message,true)}}
  async function save(){try{const body={paper_start_balance:Number($('paperStart').value),max_total_allocation:Number($('maxAllocation').value),max_position_size:Number($('maxPosition').value),max_open_positions:Number($('maxOpen').value),max_daily_loss:Number($('maxDailyLoss').value),min_signal_confidence:Number($('minConfidence').value)};const x=await json(API+'/config',{method:'POST',body:JSON.stringify(body)});renderAccount(x.account,[]);state('Paper risk settings saved.')}catch(e){state(e.message,true)}}
  async function toggle(enabled){try{await json(API+'/toggle',{method:'POST',body:JSON.stringify({enabled})});state(enabled?'Moe Agent shadow mode started.':'Moe Agent stopped.');await load()}catch(e){state(e.message,true)}}
  document.addEventListener('DOMContentLoaded',()=>{$('agentLogin')?.addEventListener('click',authenticate);$('agentSave')?.addEventListener('click',save);$('agentStart')?.addEventListener('click',()=>toggle(true));$('agentStop')?.addEventListener('click',()=>toggle(false));load();setInterval(()=>{if(token())load()},30000)});
  window.addEventListener('basedmoer:wallet',()=>{sessionStorage.removeItem(tokenKey);sessionStorage.removeItem('moeBasePermission');setTimeout(load,100)});
})();
import('/base-account.js').catch(err=>console.warn('Base Account module unavailable:',err));
