(function(){
  const API='https://moe-ai-production.up.railway.app';
  const tokenKey='moeAgentSession';
  const preview=new URLSearchParams(location.search).get('preview')==='holder';
  const money=n=>Number(n||0).toLocaleString();
  function token(){return sessionStorage.getItem(tokenKey)||''}
  function wallet(){return sessionStorage.getItem('basedMoerWallet')||''}
  async function req(path,opts={}){const t=token(),r=await fetch(API+path,{...opts,headers:{'Content-Type':'application/json',...(t?{Authorization:'Bearer '+t}:{}),...(opts.headers||{})}}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.detail||j.error||('HTTP '+r.status));return j}
  async function authenticate(){const w=wallet();if(!w||!window.ethereum)throw new Error('Connect your holder wallet first.');const c=await req('/v1/agent/auth/challenge',{method:'POST',body:JSON.stringify({wallet_address:w})});const signature=await ethereum.request({method:'personal_sign',params:[c.message,w]});const v=await req('/v1/agent/auth/verify',{method:'POST',body:JSON.stringify({wallet_address:w,signature})});sessionStorage.setItem(tokenKey,v.session_token);return v}
  function demoProgression(){return {lifetime_xp:820,spendable_xp:820,level:4,title:'Moerverse Pilot',next_level_xp:1000,equipped:{frame:'frame_cyan_signal',header:'header_cockpit_blue',ship:'ship_moe_scout'},catalog:[
    {id:'frame_cyan_signal',type:'frame',name:'Signal Ring',xp_required:100,unlocked:true},
    {id:'header_cockpit_blue',type:'header',name:'Blue Cockpit',xp_required:250,unlocked:true},
    {id:'frame_purple_arcade',type:'frame',name:'Arcade Ring',xp_required:500,unlocked:true},
    {id:'ship_moe_scout',type:'ship',name:'Moe Scout',xp_required:750,unlocked:true},
    {id:'header_radar_elite',type:'header',name:'Radar Elite',xp_required:1000,unlocked:false},
    {id:'ship_void_runner',type:'ship',name:'Void Runner',xp_required:2500,unlocked:false}
  ]}}
  function shell(){const passport=document.querySelector('.passport');if(!passport||document.getElementById('moerXpSection'))return;const div=document.createElement('div');div.id='moerXpSection';div.className='profile-section';div.innerHTML=`<div class="section-label">MOERVERSE PROGRESSION</div><h3>MOER XP & Cosmetics Locker</h3><p style="color:var(--muted)">MOER XP is non-transferable progression. Verified Academy and game activity follows your holder wallet so your Passport can be restored when you return.</p><div class="stats-grid" style="margin-top:18px"><div class="stat-card"><span>LIFETIME XP</span><strong id="moerLifetimeXp">—</strong></div><div class="stat-card"><span>LEVEL</span><strong id="moerLevel">—</strong></div><div class="stat-card"><span>PROGRESSION TITLE</span><strong id="moerXpTitle" style="font-size:15px">—</strong></div><div class="stat-card"><span>NEXT LEVEL</span><strong id="moerNextXp">—</strong></div></div><div style="display:flex;gap:10px;flex-wrap:wrap;margin-top:16px"><button class="button" id="moerXpAuth">AUTHENTICATE PASSPORT</button><button class="button secondary" id="moerXpDaily" hidden>CLAIM DAILY +5 XP</button></div><div id="moerXpMessage" style="font-size:11px;color:#8190ad;margin-top:10px"></div><div id="moerCosmetics" style="display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:18px"></div>`;const academy=Array.from(passport.querySelectorAll('.profile-section')).find(x=>x.textContent.includes('ACADEMY ACHIEVEMENTS'));if(academy)passport.insertBefore(div,academy);else passport.appendChild(div);document.getElementById('moerXpAuth').onclick=async()=>{if(preview){msg('Creator preview: server authentication is intentionally bypassed.');return}try{msg('Signing proves wallet ownership only.');await authenticate();await load()}catch(e){msg(e.message,true)}};document.getElementById('moerXpDaily').onclick=async()=>{if(preview){msg('Creator preview only — no XP is written.');return}try{const x=await req('/v1/progression/daily-claim',{method:'POST',body:'{}'});msg(x.message);render(x.progression)}catch(e){msg(e.message,true)}}}
  function msg(t,bad=false){const e=document.getElementById('moerXpMessage');if(e){e.textContent=t;e.style.color=bad?'#ff8d9b':'#8190ad'}}
  function applyEquipped(equipped){const avatar=document.querySelector('.avatar'),passport=document.querySelector('.passport');if(avatar){avatar.classList.remove('moer-frame-cyan','moer-frame-purple');if(equipped.frame==='frame_cyan_signal')avatar.classList.add('moer-frame-cyan');if(equipped.frame==='frame_purple_arcade')avatar.classList.add('moer-frame-purple')}if(passport){passport.classList.remove('moer-header-blue','moer-header-radar');if(equipped.header==='header_cockpit_blue')passport.classList.add('moer-header-blue');if(equipped.header==='header_radar_elite')passport.classList.add('moer-header-radar')}if(equipped.ship)localStorage.setItem('moerArcadeShip',equipped.ship);else localStorage.removeItem('moerArcadeShip')}
  function previewThumb(c){if(c.id==='frame_cyan_signal')return '<div style="height:70px;margin-bottom:9px;background:url(/assets/frame1.png) center/contain no-repeat,radial-gradient(circle,#07131a 0 38%,#0e8290 39% 43%,transparent 44%)"></div>';if(c.id==='frame_purple_arcade')return '<div style="height:70px;margin-bottom:9px;background:url(/assets/frame2.png) center/contain no-repeat,radial-gradient(circle,#13061e 0 38%,#67209d 39% 43%,transparent 44%)"></div>';if(c.type==='ship')return '<div style="height:70px;margin-bottom:9px;background:url(/assets/spaceship-main.png) center/contain no-repeat;image-rendering:pixelated;transform:rotate(90deg)"></div>';return '<div style="height:70px;margin-bottom:9px;border:1px solid #26375b;background:linear-gradient(135deg,#081426,#22103c)"></div>'}
  function render(p){document.getElementById('moerLifetimeXp').textContent=money(p.lifetime_xp)+' XP';document.getElementById('moerLevel').textContent=p.level;document.getElementById('moerXpTitle').textContent=p.title;document.getElementById('moerNextXp').textContent=p.next_level_xp?money(p.next_level_xp)+' XP':'MAX';document.getElementById('moerXpAuth').hidden=true;document.getElementById('moerXpDaily').hidden=false;const equipped=p.equipped||{};applyEquipped(equipped);document.getElementById('moerCosmetics').innerHTML=(p.catalog||[]).map(c=>{const active=equipped[c.type]===c.id;return `<div class="${c.type==='header'?'moer-panel-purple':''}" style="padding:14px;border:1px solid ${c.unlocked?'#3157a8':'#293146'};border-radius:12px;background:#0a0f18;opacity:${c.unlocked?1:.45}">${previewThumb(c)}<div style="font-size:9px;color:#74819b;font-weight:900">${c.type.toUpperCase()} • ${c.xp_required} XP</div><strong style="display:block;margin:7px 0 10px">${c.name}</strong><button class="nft-choice" data-equip="${c.id}" ${c.unlocked?'':'disabled'}>${active?'EQUIPPED':c.unlocked?'EQUIP':'LOCKED'}</button></div>`}).join('');document.querySelectorAll('[data-equip]').forEach(b=>b.onclick=async()=>{if(preview){const item=p.catalog.find(x=>x.id===b.dataset.equip);if(!item?.unlocked)return;const next={...p,equipped:{...p.equipped,[item.type]:item.id}};render(next);msg('Creator preview: cosmetic applied locally only.');return}try{const x=await req('/v1/progression/equip',{method:'POST',body:JSON.stringify({cosmetic_id:b.dataset.equip})});render(x.progression);msg('Cosmetic equipped to your Passport.')}catch(e){msg(e.message,true)}})}
  function academyLocal(){try{return JSON.parse(localStorage.getItem('moeAcademyV3')||'null')||{completed:{},scores:{}}}catch{return{completed:{},scores:{}}}}
  function renderAcademy(scores){const values=Object.values(scores||{}).map(Number).filter(Number.isFinite),done=values.filter(v=>v>=70).length,avg=values.length?Math.round(values.reduce((a,b)=>a+b,0)/values.length):0;if(document.getElementById('profileCompleted'))profileCompleted.textContent=done+' / 24';if(document.getElementById('profileAverage'))profileAverage.textContent=avg+'%'}
  function renderFlip(s){if(!s)return;if(document.getElementById('flipPlayed'))flipPlayed.textContent=s.played||0;if(document.getElementById('flipWins'))flipWins.textContent=s.wins||0;if(document.getElementById('flipRate'))flipRate.textContent=Number(s.win_rate_pct||0).toFixed(1).replace('.0','')+'%';if(document.getElementById('flipStreak'))flipStreak.textContent=s.best_streak||0}
  async function syncPassportDetails(){renderAcademy(academyLocal().scores||{});if(!token()||preview)return;try{const a=await req('/v1/ecosystem/academy/progress');const scores=a.progress?.scores||{};if(Object.keys(scores).length){const local=academyLocal();local.completed=local.completed||{};local.scores=local.scores||{};for(const [id,score] of Object.entries(scores)){local.completed[id]=Number(score)>=70;local.scores[id]=Math.max(Number(local.scores[id]||0),Number(score||0))}localStorage.setItem('moeAcademyV3',JSON.stringify(local));renderAcademy(local.scores)}}catch(e){if(!/404|not found/i.test(String(e.message)))console.warn('Academy Passport sync unavailable:',e)}try{const f=await req('/v1/ecosystem/flip/stats');renderFlip(f.stats)}catch(e){if(!/404|not found/i.test(String(e.message)))console.warn('Flip Passport sync unavailable:',e)}}
  async function load(){renderAcademy(academyLocal().scores||{});if(preview){render(demoProgression());msg('Creator preview: unlocked sample cosmetics are interactive; no holder data or XP is written.');return}if(!wallet()){msg('Connect your holder wallet first.');return}if(!token()){msg('Authenticate once to activate server-backed XP, Academy restoration and game stats.');return}try{const x=await req('/v1/progression/me');render(x.progression);await syncPassportDetails();msg('Passport progression synced to this wallet.')}catch(e){if(/session/i.test(e.message)){sessionStorage.removeItem(tokenKey)}msg(e.message,true)}}
  document.addEventListener('DOMContentLoaded',()=>{if(!location.pathname.startsWith('/profile/'))return;shell();renderAcademy(academyLocal().scores||{});setTimeout(load,500)});window.addEventListener('basedmoer:wallet',()=>setTimeout(load,200));
})();