(function(){
const currentPath=location.pathname,CONTRACT="0x5CafB7C0181fEd5b6d62AA331699989861c27AE7",BASE_CHAIN_ID="0x2105",HOLDER_PAGES=["/live/","/academy/","/moer-flip/","/arcade/","/profile/"],READ_RPCS=["https://base-rpc.publicnode.com","https://mainnet.base.org"],preview=new URLSearchParams(location.search).get("preview")==="holder";
let wallet=null,walletSource=null,isHolder=preview;
function active(p){return p==="/"?(currentPath==="/"?"active":""):currentPath.startsWith(p)?"active":""}
function shortAddress(a){return a?`${a.slice(0,6)}…${a.slice(-4)}`:"CONNECT WALLET"}
function publicLinks(){return `<a href="/" class="${active('/')}">Home</a><a href="/moerverse/" class="${active('/moerverse/')}">Moerverse</a><a href="/docs/" class="${active('/docs/')}">Docs</a>`}
function holderLinks(){if(!isHolder)return"";const q=preview?"?preview=holder":"";return `<a href="/live/${q}" class="${active('/live/')}">Live</a><a href="/academy/${q}" class="${active('/academy/')}">Academy</a><a href="/moer-flip/${q}" class="${active('/moer-flip/')}">Moer Flip Game</a><a href="/arcade/${q}" class="${active('/arcade/')}">Arcade</a><a href="/profile/${q}" class="${active('/profile/')}">Profile</a>`}
function walletControls(m=false){const c=m?"site-mobile-follow":"site-follow";return wallet?`<button class="${c} site-wallet-button">${shortAddress(wallet)}</button><button class="${c} site-disconnect-button">DISCONNECT</button>`:`<button class="${c} site-wallet-button">CONNECT WALLET</button>`}
function headerMarkup(){return `<header class="site-header"><div class="container site-nav-shell"><a class="site-brand" href="/"><img src="/assets/based-moer-logo.jpg" alt="Based Moer"><span class="site-brand-name">BASED MOER</span></a><nav class="site-desktop-nav">${publicLinks()}${holderLinks()}</nav><div class="site-wallet-controls">${walletControls()}</div><button class="site-mobile-toggle" id="siteMobileToggle">☰</button></div><div class="container site-mobile-menu" id="siteMobileMenu"><div>${publicLinks()}${holderLinks()}</div><div class="site-wallet-controls">${walletControls(true)}</div></div></header>`}
function footerMarkup(){return `<footer class="site-footer"><div class="container"><div class="footer-grid"><div><div class="footer-brand"><img src="/assets/based-moer-logo.jpg" alt="Based Moer"><strong>BASED MOER</strong></div><div class="footer-copy">Pixel-first • Built on Base<br><br>An artist-built onchain universe combining original pixel art, NFTs, Moe AI, education and interactive experiences.</div></div><div class="footer-column"><h4>Explore</h4><a href="/moerverse/">Moerverse</a><a href="/docs/">Documentation</a><a href="/status/">Release Status</a>${isHolder?`<a href="/live/${preview?'?preview=holder':''}">Live Engine</a><a href="/academy/${preview?'?preview=holder':''}">Moer Academy</a><a href="/moer-flip/${preview?'?preview=holder':''}">Moer Flip Game</a><a href="/arcade/${preview?'?preview=holder':''}">Moerverse Arcade</a>`:''}</div><div class="footer-column"><h4>Community</h4><a href="https://x.com/basedmoer" target="_blank" rel="noopener noreferrer">X</a><a href="https://discord.gg/B6Pu9fARTX" target="_blank" rel="noopener noreferrer">Discord</a><a href="https://www.youtube.com/@BasedMoer" target="_blank" rel="noopener noreferrer">YouTube</a><a href="https://basedmoer.gitbook.io/based-moer" target="_blank" rel="noopener noreferrer">Manifesto</a></div></div><div class="footer-bottom"><span>© 2026 Based Moer. Stay Based.</span><div class="footer-disclaimer">Based Moer is an independent creator project. Moe AI and Moer Academy provide experimental market-analysis and educational information only. Nothing on BasedMoer.com constitutes financial, investment or trading advice.</div></div></div></footer>`}
function render(){const h=document.getElementById('globalHeader');if(h){h.innerHTML=headerMarkup();bindHeader()}const f=document.getElementById('globalFooter');if(f)f.innerHTML=footerMarkup()}
function bindHeader(){const t=document.getElementById('siteMobileToggle'),m=document.getElementById('siteMobileMenu');if(t&&m)t.onclick=()=>{m.classList.toggle('open');t.textContent=m.classList.contains('open')?'✕':'☰'};document.querySelectorAll('.site-wallet-button').forEach(b=>b.onclick=connectWallet);document.querySelectorAll('.site-disconnect-button').forEach(b=>b.onclick=disconnectWallet)}
async function readRpc(method,params){let last;for(const url of READ_RPCS){try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params})});if(!r.ok)throw new Error(`Base RPC HTTP ${r.status}`);const x=await r.json();if(x.error)throw new Error(x.error.message||'Base RPC error');return x.result}catch(e){last=e}}throw last||new Error('Base read RPC unavailable')}
async function checkHolder(a){const p=a.toLowerCase().replace('0x','').padStart(64,'0'),r=await readRpc('eth_call',[{to:CONTRACT,data:'0x70a08231'+p},'latest']);return BigInt(r||'0x0')>0n}
function userRejected(e){const code=Number(e?.code||e?.cause?.code||0),msg=String(e?.message||'').toLowerCase();return code===4001||msg.includes('reject')||msg.includes('denied')||msg.includes('cancel')}
async function connectBaseAccount(){const module=await import('/base-login.js');return module.connectBaseAccount()}
async function connectInjectedWallet(){if(!window.ethereum)throw new Error('No injected wallet is available.');const accounts=await window.ethereum.request({method:'eth_requestAccounts'}),address=String(accounts?.[0]||'').toLowerCase();if(!/^0x[a-f0-9]{40}$/.test(address))throw new Error('Wallet did not return a valid address.');const chainId=String(await window.ethereum.request({method:'eth_chainId'})).toLowerCase();if(chainId!==BASE_CHAIN_ID)await window.ethereum.request({method:'wallet_switchEthereumChain',params:[{chainId:BASE_CHAIN_ID}]});return{address,source:'injected_wallet'}}
async function connectWallet(){try{let connected;try{connected=await connectBaseAccount()}catch(baseError){if(userRejected(baseError))throw baseError;console.warn('Base Account unavailable; trying injected wallet fallback.',baseError);connected=await connectInjectedWallet()}wallet=connected.address;walletSource=connected.source;isHolder=await checkHolder(wallet);sessionStorage.setItem('basedMoerWallet',wallet);sessionStorage.setItem('basedMoerWalletSource',walletSource);sessionStorage.setItem('basedMoerHolder',isHolder?'1':'0');render();updateHolderGate();dispatchEvent(new CustomEvent('basedmoer:wallet',{detail:{wallet,isHolder,source:walletSource}}));if(!isHolder)alert('Wallet connected, but no current holder-access NFT was found in this wallet.')}catch(e){console.error(e);if(!userRejected(e))alert('Wallet connection failed. Please try again.')}}
function disconnectWallet(){wallet=null;walletSource=null;isHolder=preview;sessionStorage.removeItem('basedMoerWallet');sessionStorage.removeItem('basedMoerWalletSource');sessionStorage.removeItem('basedMoerHolder');sessionStorage.removeItem('moeAgentSession');render();updateHolderGate();dispatchEvent(new CustomEvent('basedmoer:wallet',{detail:{wallet:null,isHolder,source:null}}))}
function updateHolderGate(){document.querySelectorAll('[data-holder-content]').forEach(e=>e.hidden=!isHolder);document.querySelectorAll('[data-holder-lock]').forEach(e=>e.hidden=isHolder)}
async function restoreWallet(){if(preview)return;const expected=String(sessionStorage.getItem('basedMoerWallet')||'').toLowerCase(),source=sessionStorage.getItem('basedMoerWalletSource')||'';if(!/^0x[a-f0-9]{40}$/.test(expected))return;try{let restored=null;if(source==='base_account'){const module=await import('/base-login.js');restored=await module.restoreBaseAccount();if(restored?.address!==expected)restored=null}else if(source==='injected_wallet'&&window.ethereum){const accounts=await window.ethereum.request({method:'eth_accounts'}),address=String(accounts?.[0]||'').toLowerCase(),chain=String(await window.ethereum.request({method:'eth_chainId'})).toLowerCase();if(address===expected&&chain===BASE_CHAIN_ID)restored={address,source}}if(!restored)return;wallet=restored.address;walletSource=restored.source;isHolder=await checkHolder(wallet);sessionStorage.setItem('basedMoerHolder',isHolder?'1':'0');render();updateHolderGate();dispatchEvent(new CustomEvent('basedmoer:wallet',{detail:{wallet,isHolder,source:walletSource}}))}catch(e){console.warn('Wallet session restore failed.',e)}}
function academyVisuals(){if(!currentPath.startsWith('/academy/'))return;const svg=(kind)=>{const base=`<svg viewBox="0 0 640 220" role="img" aria-label="Lesson diagram" style="width:100%;max-height:240px"><rect width="640" height="220" rx="14" fill="#080d15"/><g stroke="#24314a" stroke-width="1">${[40,80,120,160,200].map(y=>`<path d="M0 ${y}H640"/>`).join('')}</g>`;let body='';if(/risk|position|leverage/i.test(kind))body='<path d="M70 170L250 80L390 130L560 45" fill="none" stroke="#5f8cff" stroke-width="5"/><path d="M60 180H580" stroke="#ff7387" stroke-width="3" stroke-dasharray="9 8"/><text x="70" y="205" fill="#8c99b4">INVALIDATION / RISK</text>';else if(/fibonacci|pullback/i.test(kind))body='<path d="M70 175L310 40L560 160" fill="none" stroke="#5f8cff" stroke-width="5"/>'+[.236,.382,.5,.618,.786].map((v,i)=>`<path d="M300 ${65+i*25}H560" stroke="#6c7894"/><text x="565" y="${69+i*25}" fill="#9ba8c2">${v}</text>`).join('');else if(/wallet|contract|onchain|transaction/i.test(kind))body='<rect x="80" y="70" width="130" height="80" rx="12" fill="#101d3b" stroke="#4d7cff"/><rect x="430" y="70" width="130" height="80" rx="12" fill="#101d3b" stroke="#4d7cff"/><path d="M220 110H420" stroke="#67f398" stroke-width="4"/><text x="105" y="116" fill="white">WALLET</text><text x="452" y="116" fill="white">ONCHAIN</text>';else body='<g stroke="#d8e2f7" stroke-width="3">'+[100,150,200,250,300,350,400,450,500].map((x,i)=>`<path d="M${x} ${70+(i%3)*25}v${75-(i%2)*20}"/><rect x="${x-9}" y="${90+(i%3)*18}" width="18" height="${28+(i%2)*18}" fill="${i%2?'#67f398':'#ff7387'}" stroke="none"/>`).join('')+'</g><path d="M70 170L180 130L290 145L400 80L550 55" fill="none" stroke="#5f8cff" stroke-width="4"/>';return base+body+'</svg>'};setTimeout(()=>document.querySelectorAll('.visual').forEach(v=>{const lesson=v.closest('.lesson'),title=lesson?.querySelector('.lesson-title strong')?.textContent||v.textContent;v.innerHTML=svg(title)}),300)}
function addStyle(href){if(document.querySelector(`link[href="${href}"]`))return;const l=document.createElement('link');l.rel='stylesheet';l.href=href;document.head.appendChild(l)}
function addScript(src,type){if(document.querySelector(`script[src="${src}"]`))return;const s=document.createElement('script');s.src=src;if(type)s.type=type;document.body.appendChild(s)}
function loadPageExtras(){addStyle('/moer-ui.css');if(currentPath.startsWith('/profile/'))addScript('/progression.js');if(currentPath.startsWith('/academy/'))addScript('/academy-xp.js');if(currentPath.startsWith('/live/'))addScript('/radar-xp.js')}
document.addEventListener('DOMContentLoaded',()=>{render();updateHolderGate();restoreWallet();academyVisuals();loadPageExtras();if(preview)document.body.classList.add('holder-preview');if(window.ethereum){window.ethereum.on?.('accountsChanged',()=>location.reload());window.ethereum.on?.('chainChanged',()=>location.reload())}if(HOLDER_PAGES.some(p=>currentPath.startsWith(p)))document.body.classList.add('holder-route')})
})();