/* Research page controller: explicit login, private views, no startup API calls. */
(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.MoerHolderPage=factory();})(typeof globalThis==='object'?globalThis:this,function(){
'use strict';
const error=()=>{throw new Error('INVALID_RESPONSE');};
const object=x=>x&&typeof x==='object'&&!Array.isArray(x);
const exact=(x,required,optional=[])=>{if(!object(x)||required.some(k=>!(k in x))||Object.keys(x).some(k=>!required.includes(k)&&!optional.includes(k)))error();};
const identifier=x=>{if(typeof x!=='string'||!/^[a-f0-9]{32}$/.test(x))error();return x;};
const number=x=>typeof x==='number'&&Number.isFinite(x)&&x>=0&&x<=1e18;
function spec(s,pairs){exact(s,['entity','condition']);exact(s.entity,['kind','network','identity']);exact(s.condition,['field','operator','value','unit']);if(s.entity.kind!=='market'||s.entity.network!=='kraken'||!pairs.includes(s.entity.identity)||s.condition.field!=='price'||!['gte','lte'].includes(s.condition.operator)||!number(s.condition.value)||s.condition.unit!=='USD')error();return s;}
function result(r,pairs){exact(r,['outcome','reason','entity','field','value','unit','observed_at','available_at','asof']);if(!['met','unmet'].includes(r.outcome)||r.reason!=='condition_checked'||r.field!=='price'||r.unit!=='USD'||!['value','observed_at','available_at','asof'].every(k=>number(r[k]))||!['observed_at','available_at','asof'].every(k=>r[k]<=1e12))error();if(!(r.observed_at<=r.available_at&&r.available_at<=r.asof))error();spec({entity:r.entity,condition:{field:r.field,operator:'gte',value:r.value,unit:r.unit}},pairs);return r;}
function watch(w,pairs){exact(w,['task_id','status','spec','delivery_enabled','execution_enabled'],['completion_result']);identifier(w.task_id);if(!['pending','claimed','completed','cancelled'].includes(w.status)||w.delivery_enabled!==false||w.execution_enabled!==false)error();spec(w.spec,pairs);if(w.completion_result!==undefined&&w.completion_result!==null){const r=result(w.completion_result,pairs);if(w.status!=='completed'||r.entity.kind!==w.spec.entity.kind||r.entity.network!==w.spec.entity.network||r.entity.identity!==w.spec.entity.identity||r.field!==w.spec.condition.field||r.unit!==w.spec.condition.unit)error();const met=w.spec.condition.operator==='gte'?r.value>=w.spec.condition.value:r.value<=w.spec.condition.value;if((r.outcome==='met')!==met)error();}return w;}
function notice(n,pairs){exact(n,['notification_id','task_id','result','created','state','external_delivery_enabled','execution_enabled'],['read_at']);identifier(n.notification_id);identifier(n.task_id);if((!number(n.created)||n.created>1e12)||!['unread','read'].includes(n.state)||n.external_delivery_enabled!==false||n.execution_enabled!==false||(n.read_at!==undefined&&n.read_at!==null&&(!number(n.read_at)||n.read_at>1e12)))error();if(n.state==='read'&&(!number(n.read_at)||n.read_at<n.created))error();if(n.result?.asof>n.created)error();if(n.state==='unread'&&n.read_at!==undefined&&n.read_at!==null)error();result(n.result,pairs);if(n.result.outcome!=='met')error();return n;}
function createPage({document,eventTarget,config={},fetch,getWallet,signChallenge,prepareProvider,sessionModule,clientModule}={}){
 if(config.enabled===true&&config.loginProofVersion!=='moer-staging-eoa-v1')throw new Error('EXPLICIT_PILOT_PROOF_REQUIRED');
 const $=id=>document.getElementById(id),pairs=Array.isArray(config.allowedPairs)?config.allowedPairs.slice():[];
 const timeoutMs=Number.isInteger(config.operationTimeoutMs)&&config.operationTimeoutMs>0&&config.operationTimeoutMs<=120000?config.operationTimeoutMs:60000;
 let generation=0,busy=false,disposed=false,auth,client,lastNotice=null,cursor=null,prepared=null,loginActiveVersion=null;const providers=new Map();
 const controls=['login','createWatch','readWatch','cancelWatch','refreshInbox','nextInbox','readNotice','ackNotice'];
 function status(text){$('pageStatus').textContent=text;}
 function clearViews(){$('watchView').textContent='';$('noticeView').textContent='';$('inbox').replaceChildren();$('watchId').value='';$('noticeId').value='';cursor=null;lastNotice=null;}
 function buttons(){const signed=!!auth?.getSession();for(const name of controls)$(name).disabled=config.enabled!==true||disposed||busy||(name!=='login'&&!signed);$('nextInbox').disabled=$('nextInbox').disabled||!cursor;}
 function invalidate(){generation++;prepared=null;loginActiveVersion=null;busy=false;auth?.invalidate();client?.invalidate();clearViews();status(config.enabled===true?'Wallet authority changed. Log in again.':'This research room is disabled until its reviewed API configuration is supplied.');buttons();}
 eventTarget.addEventListener('basedmoer:wallet',invalidate);
 auth=sessionModule.createSession({enabled:config.enabled===true,baseURL:config.apiOrigin,allowedOrigins:config.approvedApiOrigins||[],loginProofVersion:config.loginProofVersion,audience:config.audience??null,fetch,getWallet,signChallenge:async(message,address)=>{const version=loginActiveVersion;if(version===null||!prepared||prepared.version!==version)throw new Error('STALE_SIGNER');await checkProvider(prepared.provider,version);if(loginActiveVersion!==version)throw new Error('STALE_SIGNER');const signed=await signChallenge(message,address,prepared);if(loginActiveVersion!==version)throw new Error('STALE_SIGNER');await checkProvider(prepared.provider,version);return signed;},eventTarget,onChange:()=>{clearViews();buttons();status(config.enabled===true?(auth?.getSession()?'Holder authority verified.':'Log in again with your current holder wallet.'):'This research room is disabled until its reviewed API configuration is supplied.');}});
 client=clientModule.createClient({enabled:config.enabled===true,baseURL:config.apiOrigin,allowedOrigins:config.approvedApiOrigins||[],allowedPairs:pairs,fetch,getSession:auth.getSession,onUnauthorized:invalidate,eventTarget});
 function current(version,start){if(disposed||version!==generation)return false;if(!start)return true;const now=auth.getSession();return !!now&&now.wallet===start.wallet&&now.token===start.token;}
 async function run(operation,login=false){if(disposed||busy||config.enabled!==true)return;if(!login&&!auth.getSession()){status('Log in with your current holder wallet.');return;}if(login){generation++;auth.invalidate();client.invalidate();clearViews();}const version=generation,start=login?null:auth.getSession();if(login)loginActiveVersion=version;busy=true;buttons();status(login?'Confirm the holder login signature in your wallet.':'Checking your private watch state…');let timer;try{const render=await Promise.race([(async()=>{if(!login)await protectedProvider(version,start);const render=await operation(version);if(!login)await protectedProvider(version,start);return render;})(),new Promise((_,reject)=>{timer=setTimeout(()=>{if(version===generation&&!disposed){invalidate();status('Request timed out. Log in again.');}reject(new Error('OPERATION_TIMEOUT'));},timeoutMs);})]);if(!current(version,start))return;render?.();status(login?'Holder login verified. Watches use last-trade observations.':'Updated. In-app notices only; external delivery and trading are disabled.');}catch(e){if(current(version,start))status(e?.code==='AUTH_REQUIRED'?'Holder login expired or access was denied.':'Unable to complete this request. Check your wallet, inputs and connection.');}finally{clearTimeout(timer);if(login&&loginActiveVersion===version)loginActiveVersion=null;if(version===generation){busy=false;buttons();}}}
 async function readyProvider(version){if(typeof prepareProvider!=='function')throw new Error('PROVIDER_REQUIRED');const chosen=await prepareProvider();if(!current(version,null))throw new Error('STALE_CONTEXT');const provider=chosen?.provider||chosen;if(!provider?.request||typeof provider.on!=='function'||typeof provider.removeListener!=='function')throw new Error('PROVIDER_EVENTS_REQUIRED');for(const [previous,listener] of providers){if(previous!==provider){for(const name of ['accountsChanged','chainChanged','disconnect'])previous.removeListener(name,listener);providers.delete(previous);}}prepared={provider,source:chosen?.source,version};if(!providers.has(provider)){const listener=()=>{if(prepared?.provider===provider)invalidate();};for(const name of ['accountsChanged','chainChanged','disconnect'])provider.on(name,listener);providers.set(provider,listener);}await checkProvider(provider,version);}
 async function checkProvider(provider,version){const chain=await provider.request({method:'eth_chainId'});if(loginActiveVersion!==version||!current(version,null)||String(chain).toLowerCase()!=='0x2105')throw new Error('BASE_REQUIRED');const accounts=await provider.request({method:'eth_accounts'});if(loginActiveVersion!==version||!current(version,null)||String(accounts?.[0]||'').toLowerCase()!==String(getWallet()||'').toLowerCase())throw new Error('WALLET_REQUIRED');}
 async function protectedProvider(version,start){
  try{if(!prepared?.provider||!current(version,start))throw new Error('STALE_PROVIDER');const provider=prepared.provider;const chain=await provider.request({method:'eth_chainId'});if(!current(version,start))throw new Error('STALE_PROVIDER');const accounts=await provider.request({method:'eth_accounts'});if(!current(version,start)||String(chain).toLowerCase()!=='0x2105'||String(accounts?.[0]||'').toLowerCase()!==start.wallet)throw new Error('PROVIDER_CHANGED');}
  catch(error){if(current(version,start))invalidate();throw error;}
 }
 $('login').onclick=()=>run(async version=>{await readyProvider(version);if(!current(version,null))throw new Error('STALE_CONTEXT');await auth.authenticate();return ()=>{};},true);
 $('createWatch').onclick=()=>run(async()=>{const value=Number($('threshold').value);if(!$('threshold').value.trim()||!number(value))throw new Error('INVALID_INPUT');const payload={request_key:$('requestKey').value,spec:{entity:{kind:'market',network:'kraken',identity:$('market').value},condition:{field:'price',operator:$('operator').value,value,unit:'USD'}}};const row=watch(await client.createWatch(payload),pairs);return ()=>{ $('watchId').value=row.task_id;renderWatch(row);};});
 function renderWatch(row){$('watchView').textContent=row.spec.entity.identity+' · '+row.status+' · last trade '+row.spec.condition.operator+' '+row.spec.condition.value+' USD\nWatch ID: '+row.task_id;}
 $('readWatch').onclick=()=>run(async()=>{const id=$('watchId').value,row=watch(await client.getWatch(id),pairs);if(row.task_id!==id)error();return ()=>renderWatch(row);});
 $('cancelWatch').onclick=()=>run(async()=>{const id=$('watchId').value,row=watch(await client.cancelWatch(id),pairs);if(row.task_id!==id)error();return ()=>renderWatch(row);});
 function renderNotice(row){lastNotice=row;$('noticeId').value=row.notification_id;$('noticeView').textContent=row.result.entity.identity+' · '+row.state+' · observed last trade '+row.result.value+' '+row.result.unit+'\nObserved: '+new Date(row.result.observed_at*1000).toISOString()+'\nWatch ID: '+row.task_id;}
 function listing(beforeId){const version=generation,start=auth.getSession();return run(async()=>{const data=await client.listNotifications({limit:20,...(beforeId?{beforeId}:{})});exact(data,['notifications','external_delivery_enabled'],['next_before_id']);if(data.external_delivery_enabled!==false||!Array.isArray(data.notifications)||data.notifications.length>20)error();const rows=data.notifications.map(n=>notice(n,pairs));if(new Set(rows.map(r=>r.notification_id)).size!==rows.length)error();const next=data.next_before_id==null?null:identifier(data.next_before_id);if(next&&(!rows.length||next!==rows[rows.length-1].notification_id))error();return ()=>{cursor=next;$('inbox').replaceChildren();for(const row of rows){const b=document.createElement('button');b.type='button';b.className='inbox-item';b.textContent=row.result.entity.identity+' · '+row.state+' · '+row.notification_id;b.onclick=()=>{if(current(version,start)){renderNotice(row);}};$('inbox').appendChild(b);}if(!rows.length)$('inbox').textContent='No in-app notices in this page.';};});}
 $('refreshInbox').onclick=()=>listing();$('nextInbox').onclick=()=>listing(cursor);
 $('readNotice').onclick=()=>run(async()=>{const id=$('noticeId').value,row=notice(await client.getNotification(id),pairs);if(row.notification_id!==id)error();return ()=>renderNotice(row);});
 $('ackNotice').onclick=()=>run(async()=>{const id=$('noticeId').value,row=notice(await client.acknowledgeNotification(id),pairs);if(row.notification_id!==id||row.state!=='read')error();return ()=>renderNotice(row);});
 for(const pair of pairs){const option=document.createElement('option');option.value=pair;option.textContent=pair;$('market').appendChild(option);}
 status(config.enabled===true?'Connect your Base holder wallet, then choose Log in.':'This research room is disabled until its reviewed API configuration is supplied.');buttons();
 return Object.freeze({invalidate,dispose:()=>{disposed=true;generation++;auth.dispose();client.dispose();for(const [provider,listener] of providers)for(const name of ['accountsChanged','chainChanged','disconnect'])provider.removeListener(name,listener);eventTarget.removeEventListener('basedmoer:wallet',invalidate);clearViews();buttons();},getSession:auth.getSession});
}
return Object.freeze({createPage,validateWatch:watch,validateNotice:notice});
});
