(function(){
const preview=new URLSearchParams(location.search).get('preview')==='holder';
const STORAGE='moeAcademyV3';
const TRACKS=[
{id:'foundations',name:'Market Foundations',summary:'Read price as a sequence of auctions, swings and regimes before applying any setup.',modules:[
{title:'01 — Price, Timeframes & Market Structure',body:`<p><strong>Market structure</strong> is a consistent description of meaningful swing highs and swing lows on a chosen timeframe. An uptrend is commonly described as a sequence of higher swing highs and higher swing lows; a downtrend as lower swing highs and lower swing lows. A range forms when price repeatedly trades between boundaries without persistent directional structure.</p><p>The same asset can be bullish on the daily chart and bearish on a 15-minute chart. That is not a contradiction: each timeframe compresses different information. Always state the timeframe and the swing definition before labeling structure.</p><h4>Key rule</h4><p>Structure is descriptive, not predictive. A higher high does not guarantee another higher high.</p>`,practice:'Open one liquid market on 1D, 4H and 15m. Mark the last five meaningful swings on each and write one sentence describing each timeframe.',q:'Which statement is correct?',a:['Market structure depends on timeframe and swing definition','A higher high guarantees continuation','All timeframes must show the same trend'],correct:0,visual:'structure'},
{title:'02 — Trend, Range, Expansion & Compression',body:`<p>A useful <strong>market regime</strong> describes more than direction. Directional expansion tends to show larger displacement and persistent closes in one direction. Compression shows reduced range and overlapping candles. A range is a balanced auction between visible boundaries. Transition occurs when the behavior changes.</p><p>Strategies are regime-dependent. A range-reversion idea can fail badly when genuine expansion begins, while breakout ideas can be chopped up inside balance.</p><h4>Practical checklist</h4><p>Ask: Are swings directional? Is realized range expanding or contracting? Are candles overlapping? Is price accepting outside prior balance?</p>`,practice:'Find one example each of expansion, compression and range behavior. Write what evidence made you classify each one.',q:'Why classify regime?',a:['Because a strategy can behave differently across regimes','Because regime predicts the next candle with certainty','Because ranges never break'],correct:0,visual:'regime'},
{title:'03 — Support, Resistance & Liquidity',body:`<p>Support and resistance are best treated as <strong>areas of prior interaction</strong>, not exact magical lines. Prior highs/lows, repeated reaction areas and range edges can attract orders and attention.</p><p>Visible highs and lows may also contain clustered stop orders. Price can trade through an obvious level and then reclaim it, so a touch or wick alone is not sufficient confirmation of continuation or reversal.</p><h4>Better question</h4><p>Instead of “Will this line hold?”, ask “How does price behave when it reaches this area: reject, accept, break, or reclaim?”</p>`,practice:'Mark five prior highs/lows and record whether the next interaction rejected, accepted through, or reclaimed the level.',q:'A support/resistance level is best treated as:',a:['An area requiring confirmation','A guaranteed reversal','A fixed law of price'],correct:0,visual:'sr'}]},
{id:'price',name:'Price Action & Pullbacks',summary:'Understand candle anatomy, structural breaks, displacement and Fibonacci as measurement.',modules:[
{title:'04 — Candle Anatomy: Body, Wick & Close',body:`<p>A candle records open, high, low and close for one period. The <strong>body</strong> is the distance between open and close. The <strong>wicks</strong> show the extremes traded outside the body.</p><p>A large body relative to recent candles can indicate displacement; a long wick can reflect rejection, volatility or a temporary liquidity sweep. Meaning comes from context, location and follow-through—not from a single candle shape.</p><h4>Moe Scanner relevance</h4><p>Our scanner explicitly measures body efficiency and body size relative to prior candles rather than treating every large-looking candle equally.</p>`,practice:'Compare 20 candles. Record body size, total range and close location. Note which ones actually changed structure.',q:'What does a wick prove by itself?',a:['Nothing about future direction','That price must reverse','That volume was high'],correct:0,visual:'candles'},
{title:'05 — Break of Structure, Displacement & Failure',body:`<p>A structural break occurs when price moves beyond a previously defined swing level according to a consistent rule. A robust breakout test should distinguish a small marginal poke from meaningful <strong>displacement through structure</strong>.</p><p>Follow-through matters. A break can fail if price quickly returns inside the prior range. Therefore breakout systems should define the level, required close behavior, displacement and invalidation before the event occurs.</p><h4>Failure pattern</h4><p>Break → no acceptance → reclaim of old range. This is different from a break that holds and later retests.</p>`,practice:'Collect ten historical breaks and classify them as continuation, failed break/reclaim, or unresolved.',q:'What makes a structural break useful in a system?',a:['A predefined, repeatable definition','Calling every wick a breakout','Changing the level after the move'],correct:0,visual:'breakout'},
{title:'06 — Fibonacci Pullback as a Coordinate System',body:`<p>Fibonacci retracement levels such as 0.236, 0.382, 0.5, 0.618 and 0.786 are best used as <strong>standardized coordinates</strong> inside a measured move. They do not cause reversals.</p><p>Moe Scanner v3.1 measures a qualifying structure-break leg and uses a predefined pullback zone. The value is consistency: every setup is measured with the same geometry instead of drawing levels differently after seeing the outcome.</p><p>In the current v3.1 framework the working entry zone is 0.50–0.786 of the measured leg, with invalidation at the leg origin and a predefined extension target.</p>`,practice:'Measure five clean impulse legs and note the deepest retracement before continuation or invalidation.',q:'Why are Fibonacci levels useful to software?',a:['They standardize measurement','They guarantee reversals','They eliminate invalidation'],correct:0,visual:'fib'}]},
{id:'risk',name:'Risk & Trade Math',summary:'Quantify invalidation, size, leverage and expected value before discussing returns.',modules:[
{title:'07 — Invalidation & Stop Logic',body:`<p>An invalidation level defines where the original setup thesis is no longer valid. It should come from the logic of the setup, not from the amount of money someone hopes to lose.</p><p>A stop order is an execution tool used to enforce that risk boundary. Slippage can cause the realized exit to differ from the requested stop, especially in fast or illiquid markets.</p><h4>Do not move the goalposts</h4><p>If invalidation changes after price moves against the setup, historical evaluation becomes unreliable.</p>`,practice:'Write five hypothetical setup statements containing entry condition, invalidation condition and why that invalidation makes sense.',q:'Invalidation should primarily come from:',a:['The setup logic','A desired profit target','A random percentage'],correct:0,visual:'risk'},
{title:'08 — Position Sizing, Exposure & Leverage',body:`<p>Position sizing converts a price stop into account risk. A basic risk model is: <strong>risk amount = position size × percentage move to invalidation</strong>, before fees and slippage.</p><p>Leverage changes exposure and margin requirements; it does not improve the setup edge. Higher leverage makes small adverse moves more consequential and can introduce liquidation risk before a thesis has time to play out.</p><h4>Example</h4><p>If $100 notional has a 2% stop, theoretical price risk is about $2 before costs. A larger notional with the same stop increases dollar risk proportionally.</p>`,practice:'Calculate the position size needed to risk the same $2 with 0.5%, 1% and 2% stop distances.',q:'Leverage mainly changes:',a:['Exposure and margin sensitivity','The probability the setup is correct','Market structure'],correct:0,visual:'sizing'},
{title:'09 — R-Multiples, Win Rate & Expectancy',body:`<p>An <strong>R-multiple</strong> expresses an outcome relative to initial planned risk. A +2R trade gained twice the initial risk; a -1R trade lost one unit of planned risk.</p><p>Expectancy combines win probability and payoff: <strong>E = P(win) × average win − P(loss) × average loss</strong>. Win rate alone is incomplete. A 40% win-rate system can be positive if wins are sufficiently larger than losses; a 70% system can be negative if losses are much larger.</p><p>Expectancy estimated from a small sample is uncertain and can change by regime.</p>`,practice:'Compute expectancy for: 45% wins averaging +2R and 55% losses averaging -1R.',q:'Which is enough by itself to prove edge?',a:['Neither win rate nor R:R alone','A high win rate alone','A high target alone'],correct:0,visual:'expectancy'}]},
{id:'systems',name:'Strategy & Evaluation',summary:'Turn a chart idea into explicit rules, then evaluate it without rewriting history.',modules:[
{title:'10 — From Idea to Rule-Based Strategy',body:`<p>A systematic strategy needs explicit definitions for market universe, timeframe, setup condition, entry, invalidation, target, expiration and position sizing. If two people cannot apply the rules to the same historical data and reach similar decisions, the rules are still too ambiguous.</p><p>Good rules also define when <em>not</em> to trade: conflicting regime, insufficient liquidity, stale setup, poor reward-to-risk, or missing data.</p>`,practice:'Rewrite one discretionary setup as a yes/no checklist containing at least eight explicit conditions.',q:'A strategy rule should be:',a:['Defined before observing the outcome','Changed after every loss','Based only on visual intuition'],correct:0,visual:'rules'},
{title:'11 — Backtest, Walk-Forward & Forward Paper',body:`<p>A backtest applies rules to historical data. A <strong>walk-forward</strong> process repeatedly evaluates rules on later unseen windows rather than optimizing and judging on the same sample. Forward paper testing then observes the frozen strategy on new live data without risking capital.</p><p>Historical testing can suffer look-ahead bias, survivorship bias, data-quality errors and overfitting. Live execution adds latency, spread, fees, slippage and missed fills.</p><h4>Moerverse rule</h4><p>Historical validation, forward paper results and eventual live results must remain separate cohorts.</p>`,practice:'List five ways a historical backtest can overstate live performance.',q:'Why separate backtest and forward results?',a:['They have different information and execution conditions','They are always identical','Forward testing guarantees profit'],correct:0,visual:'walkforward'},
{title:'12 — Journaling, Versioning & No Look-Ahead',body:`<p>Every signal should preserve its original timestamp, parameters, strategy version and outcome lifecycle. Versioning prevents results from materially different rules being blended into one performance number.</p><p><strong>No look-ahead</strong> means the decision can only use data available at that timestamp. A daily trend filter, for example, should use a closed daily candle rather than information from a candle that had not finished yet.</p>`,practice:'Design a signal record containing timestamp, model version, inputs, entry zone, invalidation, target, state transitions and final result.',q:'Why store strategy version with every signal?',a:['To keep results from different rules separate','To increase leverage','To edit old losses'],correct:0,visual:'version'}]},
{id:'scanner',name:'Moe Scanner v3.1',summary:'Learn exactly what the current production scanner measures and what it does not claim.',modules:[
{title:'13 — v3.1 Structure-Break Qualification',body:`<p>Moe Scanner v3.1 begins with a 4H structural break. It evaluates the breakout candle using measurable evidence including body efficiency, body size relative to prior candles, volume ratio, displacement through structure and close location.</p><p>The breakout evidence score is not a prophecy. It is a deterministic summary of whether a candle resembles the pattern defined by the strategy. v3.1 rejects weak breakout evidence before the pullback is considered.</p>`,practice:'Given ten breakout candles, rank them using body efficiency, relative body size, volume, displacement and close location—without looking at future candles.',q:'The breakout score represents:',a:['Defined breakout evidence','Guaranteed probability of profit','An LLM opinion'],correct:0,visual:'scanner'},
{title:'14 — Pullback Zone, HTF Context & Quality Score',body:`<p>After a qualifying break, v3.1 maps the measured leg and monitors a 0.50–0.786 pullback zone. Higher-timeframe context uses <strong>closed 1D candles</strong> with EMA ordering and slope to classify alignment as ALIGNED, NEUTRAL or CONFLICT. Conflict is rejected.</p><p>The calibrated quality score combines capped breakout quality, move magnitude, setup freshness/age and a small non-conflict HTF contribution. Entry-zone presence is intentionally not given a bonus after historical calibration showed additive bonuses could create overconfidence.</p>`,practice:'Explain why a system may cap one feature instead of allowing an extreme value to dominate the final score.',q:'What happens to HTF CONFLICT setups in current v3.1?',a:['They are rejected','They receive a large bonus','They are automatically traded'],correct:0,visual:'htf'},
{title:'15 — Thresholds, Results & Forward Cohorts',body:`<p>The current production posting threshold is <strong>78</strong>. This threshold came from point-in-time historical validation and is not a promise of future performance. The sample around the higher thresholds is relatively small, so forward results matter more as new observations accumulate.</p><p>New forward signals are labeled with the v3.1 strategy version and forward-live-paper validation mode so they can be evaluated separately from old history. A system should not silently retune itself after every short losing or winning streak.</p>`,practice:'Write a rule for when a model change is allowed and how the new version would be evaluated before promotion.',q:'What does a historical 63% win rate at a threshold guarantee?',a:['Nothing about future outcomes','At least 63% future wins','No losing streaks'],correct:0,visual:'threshold'}]},
{id:'radar',name:'Moe Token Radar',summary:'Evaluate low/mid-cap tokens using market, liquidity, holder and security evidence without mistaking hype for quality.',modules:[
{title:'16 — Liquidity, Market Cap, FDV & Turnover',body:`<p><strong>Market capitalization</strong> approximates circulating value. <strong>FDV</strong> estimates value if the full token supply were valued at the current price. Large gaps can matter when significant supply is not circulating.</p><p>Liquidity measures how much capital supports trading around the current price. Thin liquidity can create large price impact and unreliable exits. Volume is activity, not automatically quality: extreme volume relative to tiny liquidity can reflect churn, bots or manipulation.</p>`,practice:'Compare three tokens with identical market cap but different liquidity and 24h volume. Rank execution risk and explain why.',q:'High volume by itself proves:',a:['Nothing about token quality','Strong holders','Contract safety'],correct:0,visual:'liquidity'},
{title:'17 — Holder Distribution & Wallet Behavior',body:`<p>Holder intelligence asks who owns supply and how ownership is changing. Useful features include holder growth, top-holder concentration, dev/insider exposure, tagged sniper or bundler wallets, experienced-wallet accumulation and net buy/sell behavior.</p><p>Concentration is contextual: treasury, bridge and LP contracts can appear as large holders but differ from an unrestricted externally-owned wallet. Labels need reliable data and should never be inferred from address size alone.</p>`,practice:'Create a holder-risk checklist that distinguishes LP/treasury contracts from unrestricted wallets and requires source-backed labels.',q:'A large holder address is automatically an insider?',a:['No','Yes','Only on Solana'],correct:0,visual:'holders'},
{title:'18 — Contract Safety & Radar Verdicts',body:`<p>Before a token can become execution-eligible, Radar should treat contract/security checks as a hard veto layer. Examples include honeypot behavior, sell restrictions, dangerous owner privileges, mint/freeze authority where relevant, malicious code indicators and inadequate liquidity.</p><p>A high momentum score must never override a failed safety check. The final verdict should distinguish <strong>WATCH</strong>, <strong>EARLY EXPANSION</strong>, and <strong>REJECT</strong> with reasons.</p>`,practice:'Design five hard rejection rules that cannot be overridden by social hype or price momentum.',q:'If a token scores highly on momentum but fails a honeypot check:',a:['Reject it','Increase the score','Ignore the safety result'],correct:0,visual:'security'}]},
{id:'base',name:'Base & Onchain',summary:'Understand wallets, Base transactions, smart contracts, token approvals and permission boundaries.',modules:[
{title:'19 — Wallets, Signatures & Base Network',body:`<p>A public wallet address can be shared; a private key or seed phrase controls the wallet and must never be shared. A <strong>message signature</strong> can prove control of an address without transferring assets. A transaction signature authorizes an onchain action and may spend gas or move assets.</p><p>Base mainnet uses chain ID <strong>8453</strong>. Applications should verify the chain before preparing execution so a user cannot accidentally authorize a route for the wrong network.</p>`,practice:'Classify these as public or secret: wallet address, transaction hash, seed phrase, private key, signed login message.',q:'Which must never be shared?',a:['Seed phrase/private key','Wallet address','Transaction hash'],correct:0,visual:'wallet'},
{title:'20 — Gas, Slippage, Price Impact & Routing',body:`<p>Gas is the fee paid for computation. <strong>Price impact</strong> is the change caused by the size of your trade relative to available liquidity. <strong>Slippage tolerance</strong> is the maximum execution deterioration a user is willing to accept relative to a quoted amount.</p><p>DEX routers may choose a direct pool or multi-hop route. A multi-hop route can reach deeper liquidity but adds additional pool fees and execution complexity. Quotes expire because pool state changes.</p>`,practice:'For a hypothetical $10 swap, list the fields that should be recorded before execution: route, expected output, minimum output, gas, fees, impact and quote timestamp.',q:'Slippage tolerance is:',a:['A limit on acceptable execution deterioration','A guaranteed realized price','The same thing as gas'],correct:0,visual:'route'},
{title:'21 — Spend Permissions & Revocation',body:`<p>Base Account Spend Permissions allow a user to designate a trusted spender with explicit limits. The permission includes the account, spender, token, allowance, period, start/end time, salt and extra data. Once signed and active, the spender can act within those limits without asking the user to sign every individual spend.</p><p>This is why Moe Agent should use a narrowly bounded permission instead of ever receiving a user's private key. The user can revoke a permission, and the spender can also support a spender-side revoke path.</p><h4>Important</h4><p>A permission is authority. The spender contract and operator security must be treated as critical infrastructure.</p>`,practice:'Draft a safe $10 USDC permission: correct Base account, spender, token, allowance, validity period and revocation plan.',q:'Why are spend permissions safer than giving an agent a private key?',a:['Authority can be explicitly bounded and revoked','They guarantee profitable trades','They remove smart-contract risk'],correct:0,visual:'permission'}]},
{id:'agent',name:'Moe Agent & Execution',summary:'Understand the path from signal to shadow route to risk-controlled execution.',modules:[
{title:'22 — Signal → Asset Registry → Quote',body:`<p>A centralized-market symbol such as BTCUSDT cannot simply be “traded on Base.” The execution layer first maps the signal to an explicitly supported Base asset—for example a verified cbBTC contract—through the <strong>Base Asset Registry</strong>.</p><p>Only then does the quote engine request an actual Base route and expected output. Unsupported symbols fail closed instead of guessing token addresses.</p>`,practice:'Explain why symbol-to-contract mapping must be explicit and versioned rather than inferred from ticker text.',q:'If a scanner symbol has no verified Base asset mapping:',a:['Reject execution','Guess the contract','Search social media and buy the first result'],correct:0,visual:'registry'},
{title:'23 — Execution Safety & Shadow Trading',body:`<p>The execution safety layer can veto a trade for wrong chain, unsupported asset, insufficient liquidity, excessive slippage/impact, unsafe contract, poor route, gas cost, position limits or daily-loss limits.</p><p><strong>Shadow execution</strong> uses the same signal and obtains the real route, quote, impact and gas estimate but does not broadcast the transaction. This is more realistic than simple paper PnL because it exercises the actual onchain execution path without moving funds.</p>`,practice:'Create a pre-trade checklist where every safety rule is either PASS or REJECT and no single score can override a hard rejection.',q:'Shadow execution does what?',a:['Builds the real route without broadcasting it','Moves real money secretly','Guarantees a fill'],correct:0,visual:'shadow'},
{title:'24 — Autonomous Agent Safety, Circuit Breakers & Learning',body:`<p>An autonomous trading agent should not be a free-form model with unrestricted wallet authority. Moe separates intelligence, risk, execution and memory. Deterministic limits can veto an AI recommendation.</p><p>Critical controls include maximum allowance, maximum position, maximum open positions, daily-loss limit, allowed assets/routes, maximum slippage, emergency pause, permission revocation and idempotency so a retry cannot duplicate an order.</p><p>Learning should produce versioned candidate models that are validated offline and forward-tested before promotion. Production code should not rewrite its own trading rules after each result.</p>`,practice:'Design an emergency sequence for: unsafe quote detected, operator key suspected compromised, or unexpected duplicate execution attempt.',q:'Which component should be able to veto an AI trade recommendation?',a:['Deterministic risk/safety controls','Nothing—the AI should have final authority','The profile cosmetics system'],correct:0,visual:'agent'}]}
];

const TOTAL=TRACKS.reduce((n,t)=>n+t.modules.length,0);
let active=TRACKS[0].id;
function state(){try{return JSON.parse(localStorage.getItem(STORAGE))||{completed:{},scores:{}}}catch{return{completed:{},scores:{}}}}
function save(s){localStorage.setItem(STORAGE,JSON.stringify(s));}
function idFor(ti,mi){return TRACKS[ti].id+'-'+(mi+1)}
function visual(kind){
 const base='<svg viewBox="0 0 720 250" role="img" aria-label="Educational diagram"><rect width="720" height="250" rx="14" fill="#07101d"/><g stroke="#162944" stroke-width="1">'+[50,100,150,200].map(y=>`<path d="M0 ${y}H720"/>`).join('')+'</g>';
 const txt=(x,y,s,c='#9eb9df')=>`<text x="${x}" y="${y}" fill="${c}" font-size="12" font-family="monospace">${s}</text>`;
 let b='';
 if(kind==='structure') b='<path d="M50 190L150 125L240 160L345 80L440 125L560 45L660 85" fill="none" stroke="#58c8ff" stroke-width="5"/>'+txt(130,115,'HL')+txt(325,70,'HH')+txt(425,115,'HL')+txt(545,35,'HH');
 else if(kind==='regime') b='<path d="M40 180L160 70L260 145" fill="none" stroke="#58c8ff" stroke-width="5"/><path d="M285 125L440 125" stroke="#aa79ff" stroke-width="55" opacity=".18"/><path d="M470 150L520 130L565 142L610 120L670 132" fill="none" stroke="#7bf2c5" stroke-width="4"/>'+txt(60,220,'EXPANSION')+txt(325,220,'BALANCE')+txt(535,220,'COMPRESSION');
 else if(kind==='sr') b='<rect x="55" y="65" width="610" height="34" fill="#8e5cff" opacity=".18"/><rect x="55" y="170" width="610" height="34" fill="#3dcaff" opacity=".18"/><path d="M70 185L170 80L260 185L355 82L450 185L545 78L650 125" fill="none" stroke="#eef7ff" stroke-width="4"/>'+txt(62,58,'RESISTANCE / PRIOR LIQUIDITY')+txt(62,225,'SUPPORT / PRIOR LIQUIDITY');
 else if(kind==='candles') b=[100,170,240,310,380,450,520,590].map((x,i)=>{let top=45+(i%3)*22,bot=195-(i%2)*30,up=i%2===0,bodyTop=up?95+(i%3)*10:70+(i%3)*15,bodyH=55;return `<path d="M${x} ${top}V${bot}" stroke="#d8e8ff" stroke-width="3"/><rect x="${x-12}" y="${bodyTop}" width="24" height="${bodyH}" fill="${up?'#52e6ae':'#ff7387'}"/>`}).join('')+txt(70,230,'WICK = EXTREME   BODY = OPEN↔CLOSE');
 else if(kind==='breakout') b='<path d="M40 160H360" stroke="#aa79ff" stroke-width="3" stroke-dasharray="8 7"/><path d="M55 205L130 145L220 190L310 150L390 72L470 60L560 45L650 30" fill="none" stroke="#58c8ff" stroke-width="5"/><rect x="365" y="55" width="38" height="105" fill="#52e6ae" opacity=".75"/>'+txt(45,150,'PRIOR STRUCTURE')+txt(420,190,'DISPLACEMENT + CLOSE THROUGH LEVEL');
 else if(kind==='fib') b='<path d="M70 205L350 35L655 185" fill="none" stroke="#58c8ff" stroke-width="5"/>'+[.236,.382,.5,.618,.786].map((v,i)=>`<path d="M350 ${65+i*31}H655" stroke="${i>=2?'#9c6cff':'#53627a'}" stroke-width="2"/><text x="660" y="${69+i*31}" fill="#aab9d1" font-size="11">${v}</text>`).join('')+txt(430,225,'0.50–0.786 PULLBACK ZONE');
 else if(kind==='risk') b='<path d="M75 170L250 95L430 135L650 55" fill="none" stroke="#58c8ff" stroke-width="5"/><path d="M55 205H665" stroke="#ff7387" stroke-width="4" stroke-dasharray="10 8"/>'+txt(60,226,'INVALIDATION — setup thesis no longer valid');
 else if(kind==='sizing') b='<rect x="80" y="55" width="160" height="140" rx="12" fill="#0e2139" stroke="#58c8ff"/><rect x="285" y="95" width="160" height="100" rx="12" fill="#191534" stroke="#aa79ff"/><rect x="490" y="135" width="160" height="60" rx="12" fill="#112a26" stroke="#52e6ae"/>'+txt(105,120,'WIDE STOP')+txt(305,140,'MEDIUM STOP')+txt(510,170,'TIGHT STOP')+txt(105,220,'Same $ risk ⇒ different position size');
 else if(kind==='expectancy') b='<rect x="70" y="55" width="250" height="125" rx="12" fill="#0f2036" stroke="#58c8ff"/><rect x="400" y="55" width="250" height="125" rx="12" fill="#221535" stroke="#aa79ff"/>'+txt(105,100,'P(win) × Avg Win')+txt(430,100,'P(loss) × Avg Loss')+txt(235,220,'EXPECTANCY = WIN TERM − LOSS TERM','#7bf2c5');
 else if(kind==='rules') b=['UNIVERSE','TIMEFRAME','SETUP','ENTRY','INVALIDATION','TARGET','EXPIRY','SIZE'].map((s,i)=>`<rect x="${45+(i%4)*165}" y="${45+Math.floor(i/4)*90}" width="140" height="55" rx="9" fill="#0d1b2f" stroke="#345b88"/>${txt(60+(i%4)*165,78+Math.floor(i/4)*90,s)}`).join('');
 else if(kind==='walkforward') b='<path d="M50 125H670" stroke="#37516f" stroke-width="7"/>'+[['TRAIN',70,190],['TEST',270,130],['FORWARD',420,210]].map(([s,x,w],i)=>`<rect x="${x}" y="${85+i*35}" width="${w}" height="55" rx="8" fill="${i===0?'#12315a':i===1?'#2b1b54':'#123c32'}"/>${txt(x+18,118+i*35,s)}`).join('');
 else if(kind==='version') b='<rect x="65" y="55" width="170" height="145" rx="12" fill="#0d1b2f" stroke="#58c8ff"/>'+txt(95,90,'SIGNAL v3.1')+txt(95,120,'timestamp')+txt(95,145,'inputs')+txt(95,170,'outcome')+'<path d="M250 125H455" stroke="#7bf2c5" stroke-width="4"/><rect x="470" y="55" width="180" height="145" rx="12" fill="#1d1535" stroke="#aa79ff"/>'+txt(500,90,'NEW VERSION')+txt(500,120,'NEW COHORT')+txt(500,150,'NO RELABELING');
 else if(kind==='scanner') b='<rect x="50" y="55" width="115" height="140" rx="9" fill="#0d1b2f" stroke="#58c8ff"/><rect x="205" y="55" width="115" height="140" rx="9" fill="#0d1b2f" stroke="#58c8ff"/><rect x="360" y="55" width="115" height="140" rx="9" fill="#0d1b2f" stroke="#58c8ff"/><rect x="515" y="55" width="150" height="140" rx="9" fill="#142b27" stroke="#52e6ae"/>'+txt(70,95,'BODY')+txt(225,95,'VOLUME')+txt(375,95,'DISPLACE')+txt(540,95,'BREAKOUT')+txt(545,125,'EVIDENCE')+txt(550,155,'SCORE');
 else if(kind==='htf') b='<rect x="55" y="50" width="190" height="150" rx="12" fill="#0e2430" stroke="#52e6ae"/>'+txt(95,85,'1D CLOSED')+txt(92,115,'EMA ORDER')+txt(98,145,'EMA SLOPE')+'<path d="M260 125H445" stroke="#58c8ff" stroke-width="4"/><rect x="460" y="50" width="200" height="150" rx="12" fill="#1c1730" stroke="#aa79ff"/>'+txt(490,85,'ALIGNED')+txt(490,120,'NEUTRAL')+txt(490,155,'CONFLICT = REJECT');
 else if(kind==='threshold') b='<path d="M60 200H670M60 40V200" stroke="#42536c"/><path d="M80 175L190 155L300 140L410 105L520 75L630 65" fill="none" stroke="#58c8ff" stroke-width="5"/><path d="M500 40V200" stroke="#aa79ff" stroke-width="3" stroke-dasharray="8 8"/>'+txt(485,225,'78')+txt(430,30,'PRODUCTION POST THRESHOLD');
 else if(kind==='liquidity') b='<rect x="55" y="55" width="180" height="145" rx="10" fill="#0d1b2f" stroke="#58c8ff"/>'+txt(80,95,'MARKET CAP')+txt(80,125,'FDV')+'<rect x="275" y="55" width="180" height="145" rx="10" fill="#102c27" stroke="#52e6ae"/>'+txt(305,95,'LIQUIDITY')+txt(305,125,'DEPTH')+'<rect x="495" y="55" width="170" height="145" rx="10" fill="#23173a" stroke="#aa79ff"/>'+txt(525,95,'VOLUME')+txt(520,125,'TURNOVER');
 else if(kind==='holders') b=[0,1,2,3,4,5,6,7].map((_,i)=>`<circle cx="${105+(i%4)*165}" cy="${80+Math.floor(i/4)*100}" r="28" fill="${i<2?'#8d5cff':'#15365a'}" stroke="#7aaeff"/><text x="${95+(i%4)*165}" y="${85+Math.floor(i/4)*100}" fill="#fff" font-size="11">${i<2?'TOP':'W'+(i+1)}</text>`).join('')+txt(220,230,'CONCENTRATION • LABELS • NET FLOW');
 else if(kind==='security') b='<path d="M360 35L620 95V145C620 190 520 222 360 238C200 222 100 190 100 145V95Z" fill="#0b1d2d" stroke="#52e6ae" stroke-width="4"/>'+['HONEYPOT','SELL RULES','OWNER PRIVILEGES','MINT/FREEZE','LIQUIDITY'].map((s,i)=>txt(245,80+i*28,'✓ '+s)).join('');
 else if(kind==='wallet') b='<rect x="70" y="65" width="190" height="120" rx="12" fill="#0d1b2f" stroke="#58c8ff"/>'+txt(110,105,'PUBLIC ADDRESS')+txt(110,140,'SIGN MESSAGE')+'<path d="M280 125H440" stroke="#52e6ae" stroke-width="4"/><rect x="460" y="65" width="190" height="120" rx="12" fill="#1d1535" stroke="#aa79ff"/>'+txt(510,105,'BASE 8453')+txt(500,140,'TRANSACTION');
 else if(kind==='route') b='<circle cx="90" cy="125" r="45" fill="#16305a"/>'+txt(72,130,'USDC')+'<path d="M140 125H300" stroke="#58c8ff" stroke-width="4"/><circle cx="360" cy="125" r="45" fill="#2a1d55"/>'+txt(340,130,'WETH')+'<path d="M410 125H570" stroke="#aa79ff" stroke-width="4"/><circle cx="630" cy="125" r="45" fill="#123d34"/>'+txt(606,130,'cbBTC')+txt(205,215,'ROUTE • FEES • GAS • IMPACT • MIN OUTPUT');
 else if(kind==='permission') b='<rect x="55" y="45" width="260" height="165" rx="12" fill="#0d1b2f" stroke="#58c8ff"/>'+['ACCOUNT','SPENDER','TOKEN','ALLOWANCE','START / END'].map((s,i)=>txt(85,80+i*27,s))+'<path d="M330 125H450" stroke="#52e6ae" stroke-width="4"/><rect x="470" y="65" width="190" height="120" rx="12" fill="#142c28" stroke="#52e6ae"/>'+txt(500,105,'BOUNDED')+txt(500,135,'REVOCABLE')+txt(500,165,'AUTHORITY');
 else if(kind==='registry') b='<rect x="45" y="75" width="180" height="100" rx="10" fill="#1e1735" stroke="#aa79ff"/>'+txt(85,115,'BTCUSDT')+txt(65,145,'SCANNER SYMBOL')+'<path d="M240 125H420" stroke="#58c8ff" stroke-width="4"/><rect x="435" y="55" width="230" height="140" rx="10" fill="#0d2b27" stroke="#52e6ae"/>'+txt(480,95,'BASE ASSET')+txt(500,125,'cbBTC')+txt(475,155,'VERIFIED CONTRACT');
 else if(kind==='shadow') b='<rect x="50" y="55" width="130" height="140" rx="10" fill="#0d1b2f" stroke="#58c8ff"/>'+txt(82,95,'SIGNAL')+'<path d="M190 125H280" stroke="#58c8ff" stroke-width="4"/><rect x="290" y="55" width="140" height="140" rx="10" fill="#1d1535" stroke="#aa79ff"/>'+txt(320,95,'QUOTE')+txt(315,125,'SAFETY')+'<path d="M440 125H530" stroke="#52e6ae" stroke-width="4"/><rect x="540" y="55" width="130" height="140" rx="10" fill="#132823" stroke="#52e6ae"/>'+txt(560,95,'SHADOW')+txt(565,125,'NO SEND')+txt(565,155,'RECORD');
 else b='<circle cx="150" cy="125" r="55" fill="#15315c" stroke="#58c8ff"/><circle cx="360" cy="125" r="55" fill="#2a1d55" stroke="#aa79ff"/><circle cx="570" cy="125" r="55" fill="#15382e" stroke="#52e6ae"/>'+txt(125,130,'BRAIN')+txt(340,130,'RISK')+txt(535,130,'EXECUTION')+'<path d="M205 125H305M415 125H515" stroke="#d7e8ff" stroke-width="3"/>';
 return base+b+'</svg>';
}
function render(){
 const s=state(),completed=Object.keys(s.completed||{}),scores=Object.values(s.scores||{}),done=completed.length,avg=scores.length?Math.round(scores.reduce((a,b)=>a+b,0)/scores.length):0;
 completedCount.textContent=`${done} / ${TOTAL}`;averageScore.textContent=avg+'%';progressText.textContent=Math.round(done/TOTAL*100)+'%';progressFill.style.width=Math.round(done/TOTAL*100)+'%';
 currentTitle.textContent=done>=24?'Moerverse Systems Analyst':done>=18?'Onchain Analyst':done>=12?'System Builder':done>=6?'Structure Reader':'Academy Initiate';
 const ach=[['Structure Reader',6],['System Builder',12],['Onchain Analyst',18],['Moerverse Systems Analyst',24],['High Conviction Learner',avg>=90&&done>0?0:999]];
 achievementCount.textContent=ach.filter(x=>x[1]===0||done>=x[1]).length;
 achievementGrid.innerHTML=ach.map(x=>`<div class="badge ${x[1]===0||done>=x[1]?'unlocked':''}"><strong>${x[0]}</strong><span>${x[1]===0||done>=x[1]?'UNLOCKED':'LOCKED'}</span></div>`).join('');
 trackNav.innerHTML=TRACKS.map(t=>`<button class="${t.id===active?'active':''}" data-track="${t.id}">${t.name}</button>`).join('');
 trackNav.querySelectorAll('button').forEach(b=>b.onclick=()=>{active=b.dataset.track;render()});
 const ti=TRACKS.findIndex(t=>t.id===active),t=TRACKS[ti];trackSummary.innerHTML=`<div class="card track-summary"><h3>${t.name}</h3><p>${t.summary}</p></div>`;
 courseList.innerHTML=t.modules.map((m,mi)=>{const id=idFor(ti,mi),complete=!!s.completed[id],score=s.scores[id];return `<article class="lesson" id="lesson-${id}"><button class="lesson-head"><div class="lesson-num">${String(ti*3+mi+1).padStart(2,'0')}</div><div class="lesson-title"><strong>${m.title}</strong><span>${complete?'Completed • '+score+'%':'Lesson + practice + knowledge check'}</span></div><div class="lesson-status ${complete?'complete':''}">${complete?'COMPLETE':'OPEN'}</div></button><div class="lesson-body"><div class="article">${m.body}<div class="visual">${visual(m.visual)}</div><div class="practice"><strong>PRACTICE</strong><br>${m.practice}</div><div class="quiz"><h4>KNOWLEDGE CHECK</h4><div class="question"><strong>${m.q}</strong>${m.a.map((a,i)=>`<label class="answer"><input type="radio" name="q-${id}" value="${i}"> ${a}</label>`).join('')}</div><button class="button quiz-submit" data-id="${id}" data-correct="${m.correct}">SUBMIT ANSWER</button><div class="quiz-result" id="result-${id}" hidden></div></div></div></div></article>`}).join('');
 document.querySelectorAll('.lesson-head').forEach(b=>b.onclick=()=>b.closest('.lesson').classList.toggle('open'));
 document.querySelectorAll('.quiz-submit').forEach(b=>b.onclick=()=>submit(b.dataset.id,Number(b.dataset.correct)));
}
function submit(id,correct){const picked=document.querySelector(`input[name="q-${id}"]:checked`),out=document.getElementById('result-'+id);if(!picked){out.hidden=false;out.className='quiz-result fail';out.textContent='Choose an answer first.';return}const ok=Number(picked.value)===correct,score=ok?100:0;out.hidden=false;out.className='quiz-result '+(ok?'pass':'fail');out.textContent=ok?'Correct — module completed at 100%.':'Not correct yet. Review the lesson and try again.';if(ok){const s=state();s.completed[id]=true;s.scores[id]=Math.max(s.scores[id]||0,score);save(s);setTimeout(render,350)}}
document.addEventListener('DOMContentLoaded',()=>{document.getElementById('academyMode').textContent=preview?'CREATOR PREVIEW — QUIZZES WORK, XP SYNC DISABLED':'HOLDER ACADEMY';render()});
})();