const test=require('node:test'),assert=require('node:assert/strict');
const {create:createState}=require('../academy-state.js');
const {create:createSync}=require('../academy-sync.js');
function fixture(){const values=new Map(),session=new Map();const local={getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v)};const store={getItem:k=>session.get(k)||null};const state=createState(local,store);const switchTo=n=>{session.set('basedMoerWallet','0x'+String(n).repeat(40));session.set('moeAgentSession','token'+n)};return {values,session,state,switchTo};}
const score={completed:{'risk-1':true},scores:{'risk-1':100}};
test('legacy anonymous state never migrates into wallet accounts',()=>{const f=fixture();f.values.set('moeAcademyV3',JSON.stringify(score));assert.deepEqual(f.state.read(),score);f.switchTo(1);assert.deepEqual(f.state.read().scores,{});f.state.write(score);f.switchTo(2);assert.deepEqual(f.state.read().scores,{});f.switchTo(1);assert.deepEqual(f.state.read(),score)});
test('failed claims retry unchanged scores and successful claims stop repeating',async()=>{const f=fixture();f.switchTo(1);f.state.write(score);let calls=0;const e=createSync(f.state,async()=>{if(++calls===1)throw Error('temporary');return {xp_awarded:10}});assert.equal((await e.sync()).failed,1);assert.equal((await e.sync()).claimed,10);assert.equal((await e.sync()).unchanged,true);assert.equal(calls,2)});
test('wallet switch during restore discards remote result',async()=>{const f=fixture();f.switchTo(1);let done;const e=createSync(f.state,()=>new Promise(r=>done=r));const pending=e.restore();f.switchTo(2);done({progress:{scores:{'risk-1':100}}});assert.equal(await pending,false);assert.deepEqual(f.state.read().scores,{})});
test('concurrent sync is single-flight and cannot submit another claim after wallet switch',async()=>{const f=fixture();f.switchTo(1);f.state.write({completed:{},scores:{a:100,b:100}});let done,calls=[];const e=createSync(f.state,(path,opts,c)=>{calls.push(c.token);return new Promise(r=>done=r)});const pending=e.sync();assert.equal((await e.sync()).busy,true);f.switchTo(2);done({xp_awarded:10});assert.equal((await pending).stale,true);assert.deepEqual(calls,['token1']);f.state.write(score);const next=e.sync();done({xp_awarded:10});assert.equal((await next).total,1);assert.deepEqual(calls,['token1','token2'])});
test('stale context writes rejected and preview never syncs',async()=>{const f=fixture();f.switchTo(1);const old=f.state.context();f.switchTo(2);assert.equal(f.state.write(score,old),false);const preview=createState({getItem:()=>null,setItem(){}},{getItem:()=>null},true);const e=createSync(preview,()=>{throw Error('must not call')});assert.equal((await e.sync()).unauthenticated,true)});
