const {test}=require('node:test'),assert=require('node:assert/strict');const moduleReview=require('../holder-intelligence/review.js');const {references,response,scannerExplanation,asOf}=require('./review_fixtures.cjs');
const detached=x=>JSON.parse(JSON.stringify(x));
test('parse bounded exact references only, unique product/ID pairs',()=>{assert.deepEqual(moduleReview.parseReferences('scanner fixture_scanner\nradar_candidate fixture_radar'),references);for(const input of ['', 'scanner id extra','wallet 0x123','scanner bad/id','scanner same\nscanner same',Array(9).fill(0).map((_,i)=>'scanner id'+i).join('\n'),'scanner '+'a'.repeat(129)])assert.throws(()=>moduleReview.parseReferences(input));});
test('valid requested scanner and radar evidence retain citations and limits',()=>{const data=response();assert.equal(moduleReview.validate(data,references),data);assert.equal(data.items[0].explanation.evidence[0].ref,'synthetic-browser:fixture_scanner');assert.equal(data.items[1].explanation.facts.price_semantics,'recorded_candidate_price_not_executable_quote');});
test('missing and untrusted records preserve abstention/unavailability',()=>{const explanation={schema_version:'moer.evidence-explanation.v1',product:'scanner',disposition:'ABSTAIN',reason_codes:['snapshot_metadata_missing'],facts:{},evidence:[],limitations:['record_explanation_only']};const items=[{reference:references[0],outcome:'abstained',explanation,next_action:'resolve_evidence_gap'},{reference:references[1],outcome:'unavailable',next_action:'record_unavailable'}];const data=response(items);assert.equal(moduleReview.validate(data,references).disposition,'abstain');});
test('coverage, order, scope, execution and memory must match exact request',()=>{for(const change of [d=>d.coverage.explained++,d=>d.coverage.scope='all_markets',d=>d.items.reverse(),d=>d.execution_enabled=true,d=>d.memory_saved=true,d=>d.conclusion='Trade now',d=>d.items[0].reference.record_id='other',d=>d.items[0].next_action='retry_later']){const data=detached(response());change(data);assert.throws(()=>moduleReview.validate(data,references));}});
test('citation chronology, record binding, cutoff and tool byte bounds fail closed',()=>{for(const change of [e=>e.evidence[0].source='<script>',e=>e.evidence[0].available_at='2026-10-04T05:00:00Z',e=>e.record.id='other',e=>e.record.table='agent_sessions',e=>e.as_of='2026-10-04T05:00:00Z',e=>e.facts.api_key='secret',e=>e.evidence.push(...Array(9).fill(e.evidence[0])),e=>e.limitations=Array(33).fill('a')]){const data=detached(response());change(data.items[0].explanation);assert.throws(()=>moduleReview.validate(data,references));}});
test('abstention cannot smuggle facts or evidence and unavailable has no explanation',()=>{const items=[{reference:references[0],outcome:'unavailable',explanation:scannerExplanation(),next_action:'record_unavailable'}];assert.throws(()=>moduleReview.validate(response(items),[references[0]]));const e={...scannerExplanation(),disposition:'ABSTAIN',reason_codes:['snapshot_metadata_missing']};const bad=response([{reference:references[0],outcome:'abstained',explanation:e,next_action:'resolve_evidence_gap'}]);assert.throws(()=>moduleReview.validate(bad,[references[0]]));});
test('renderer uses created text nodes and literal opaque citations',()=>{function node(){return {children:[],textContent:'',appendChild(v){this.children.push(v);},replaceChildren(){this.children=[];this.textContent='';},set innerHTML(_){throw Error('HTML forbidden');}};}const root=node();moduleReview.render({createElement:node},root,moduleReview.validate(response(),references));const text=n=>n.textContent+' '+n.children.map(text).join(' ');const rendered=text(root);assert.match(rendered,/synthetic-browser:fixture_scanner/);assert.match(rendered,/synthetic-browser:fixture_radar/);assert.match(rendered,/only your 2 supplied records/);assert.match(rendered,/uncalibrated quality/);assert.match(rendered,/not saved as conversation memory/);});
