const {test}=require('node:test'),assert=require('node:assert/strict');const {createPage,validateWatch,validateNotice}=require('../holder-intelligence/page.js');
const wallet='0x'+'1'.repeat(40),id='a'.repeat(32),nid='b'.repeat(32),pair='XXBTZUSD';
const spec={entity:{kind:'market',network:'kraken',identity:pair},condition:{field:'price',operator:'gte',value:2,unit:'USD'}};
const result={outcome:'met',reason:'condition_checked',entity:spec.entity,field:'price',value:3,unit:'USD',observed_at:999,available_at:999,asof:1000};
const watch={task_id:id,status:'pending',spec,delivery_enabled:false,execution_enabled:false};const notice={notification_id:nid,task_id:id,result,created:1000,state:'unread',external_delivery_enabled:false,execution_enabled:false};
function fixture(extra={}){const elements=new Map();function element(){return {value:'',textContent:'',disabled:false,children:[],appendChild(v){this.children.push(v);},replaceChildren(){this.children=[];this.textContent='';},set innerHTML(_){throw Error('HTML forbidden');}};}const get=name=>{if(!elements.has(name))elements.set(name,element());return elements.get(name);};const target=new EventTarget(),listeners=new Map(),calls=[],signs=[];let current=null,account=wallet,chain='0x2105',sessionOptions;
const provider={request:async({method})=>method==='eth_chainId'?chain:[account],on:(event,fn)=>listeners.set(event,fn),removeListener:(event,fn)=>{if(listeners.get(event)===fn)listeners.delete(event);}};
const auth={getSession:()=>current,invalidate:()=>{current=null;sessionOptions?.onChange();},dispose:()=>{current=null;},authenticate:async()=>{auth.invalidate();await sessionOptions.signChallenge('login message',wallet);current={wallet,token:'test-token',verified:true};sessionOptions.onChange();return current;}};
const client={invalidate(){},dispose(){},createWatch:async p=>{calls.push(['create',p]);return watch;},getWatch:async value=>{calls.push(['get',value]);return watch;},cancelWatch:async()=>({...watch,status:'cancelled'}),listNotifications:async()=>({notifications:[notice],external_delivery_enabled:false}),getNotification:async()=>notice,acknowledgeNotification:async()=>({...notice,state:'read',read_at:1001}),...extra.client};
const page=createPage({document:{getElementById:get,createElement:element},eventTarget:target,config:{enabled:true,loginProofVersion:'moer-staging-eoa-v1',audience:'https://test.example',apiOrigin:'https://test.example',approvedApiOrigins:['https://test.example'],allowedPairs:[pair],...extra.config},getWallet:()=>wallet,fetch:()=>{throw Error('unexpected fetch');},signChallenge:async(...args)=>{signs.push(args);return {signature:'sig'};},prepareProvider:async()=>({provider,source:'injected_wallet'}),sessionModule:{createSession:o=>{sessionOptions=o;return auth;}},clientModule:{createClient:()=>client},reviewModule:require('../holder-intelligence/review.js'),...extra.page});return {page,get,target,calls,signs,provider,listeners,auth,client,setAccount:v=>account=v,setChain:v=>chain=v,login:()=>get('login').onclick(),sessionOptions:()=>sessionOptions};}
test('page default disabled startup never reads or signs',async()=>{const f=fixture({config:{enabled:false}});assert.equal(f.calls.length,0);assert.equal(f.get('login').disabled,true);await f.login();assert.equal(f.signs.length,0);assert.match(f.get('pageStatus').textContent,/disabled/);});
test('explicit login gates actions; create/read/cancel use known watch ID',async()=>{const f=fixture();assert.equal(f.get('createWatch').disabled,true);await f.login();assert.equal(f.signs[0][2].provider,f.provider);assert.equal(f.get('createWatch').disabled,false);f.get('market').value=pair;f.get('operator').value='gte';f.get('threshold').value='2';f.get('requestKey').value='key';await f.get('createWatch').onclick();assert.equal(f.get('watchId').value,id);assert.match(f.get('watchView').textContent,/last trade/);await f.get('readWatch').onclick();await f.get('cancelWatch').onclick();assert.match(f.get('watchView').textContent,/cancelled/);});
test('notifications render plain text and ACK read state',async()=>{const f=fixture();await f.login();await f.get('refreshInbox').onclick();assert.equal(f.get('inbox').children.length,1);f.get('inbox').children[0].onclick();assert.equal(f.get('noticeId').value,nid);assert.match(f.get('noticeView').textContent,/observed last trade/);await f.get('ackNotice').onclick();assert.match(f.get('noticeView').textContent,/read/);});
test('active signer events immediately clear session and views',async()=>{for(const event of ['accountsChanged','chainChanged','disconnect']){const f=fixture();await f.login();f.get('watchView').textContent='private';f.listeners.get(event)();assert.equal(f.page.getSession(),null);assert.equal(f.get('watchView').textContent,'');assert.equal(f.get('createWatch').disabled,true);}});
test('wrong chain/account cannot reach login signing',async()=>{for(const mode of ['chain','account']){const f=fixture();if(mode==='chain')f.setChain('0x1');else f.setAccount('0x'+'2'.repeat(40));await f.login();assert.equal(f.signs.length,0);assert.equal(f.page.getSession(),null);}});
test('wallet change fences stale watch render and clears IDs',async()=>{let release;const f=fixture({client:{getWatch:()=>new Promise(r=>release=r)}});await f.login();f.get('watchId').value=id;const p=f.get('readWatch').onclick();await new Promise(r=>setImmediate(r));f.target.dispatchEvent(new Event('basedmoer:wallet'));release(watch);await p;assert.equal(f.get('watchView').textContent,'');assert.equal(f.get('watchId').value,'');});
test('stale detached inbox item cannot render across relogin',async()=>{const f=fixture();await f.login();await f.get('refreshInbox').onclick();const old=f.get('inbox').children[0];f.target.dispatchEvent(new Event('basedmoer:wallet'));await f.login();old.onclick();assert.equal(f.get('noticeView').textContent,'');});
test('strict response schema rejects unsupported data and HTML-bearing identity',async()=>{assert.throws(()=>validateWatch({...watch,wallet_address:wallet},[pair]));assert.throws(()=>validateWatch({...watch,spec:{...spec,entity:{...spec.entity,identity:'<img onerror=attack>'}}},[pair]));assert.throws(()=>validateNotice({...notice,state:'read'},[pair]));const f=fixture({client:{getWatch:async()=>({...watch,execution_enabled:true})}});await f.login();f.get('watchId').value=id;await f.get('readWatch').onclick();assert.equal(f.get('watchView').textContent,'');assert.match(f.get('pageStatus').textContent,/Unable/);});
test('malformed create input sends no request and double actions are blocked',async()=>{const f=fixture();await f.login();f.get('threshold').value='';await f.get('createWatch').onclick();assert.equal(f.calls.length,0);let release;f.client.getWatch=()=>new Promise(r=>release=r);f.get('watchId').value=id;const p=f.get('readWatch').onclick();await new Promise(r=>setImmediate(r));await f.get('createWatch').onclick();release(watch);await p;assert.equal(f.calls.length,0);});
test('dispose removes signer listeners and clears authority',async()=>{const f=fixture();await f.login();f.page.dispose();assert.equal(f.listeners.size,0);assert.equal(f.page.getSession(),null);assert.equal(f.get('login').disabled,true);});
test('signer event during signature fences verification and clears authority',async()=>{let release;const f=fixture({page:{signChallenge:()=>new Promise(r=>release=r)}});const p=f.login();await new Promise(r=>setImmediate(r));f.listeners.get('chainChanged')();release({signature:'sig'});await p;assert.equal(f.page.getSession(),null);});
test('deadline bounds provider preparation and prevents late signing',async()=>{let release;const f=fixture({config:{operationTimeoutMs:10},page:{prepareProvider:()=>new Promise(r=>release=r)}});await f.login();assert.match(f.get('pageStatus').textContent,/timed out/);release({provider:f.provider,source:'injected_wallet'});await new Promise(r=>setImmediate(r));assert.equal(f.signs.length,0);assert.equal(f.page.getSession(),null);});
test('silent provider changes deny protected dispatch and revoke authority',async()=>{for(const mode of ['chain','account']){const f=fixture();await f.login();f.get('watchId').value=id;if(mode==='chain')f.setChain('0x1');else f.setAccount('0x'+'2'.repeat(40));await f.get('readWatch').onclick();assert.equal(f.calls.length,0);assert.equal(f.page.getSession(),null);assert.equal(f.get('watchView').textContent,'');}});
test('provider change after response fences protected render',async()=>{const f=fixture();await f.login();f.get('watchId').value=id;f.client.getWatch=async()=>{f.setChain('0x1');return watch;};await f.get('readWatch').onclick();assert.equal(f.get('watchView').textContent,'');assert.equal(f.page.getSession(),null);});
test('response chronology and completion identity must be consistent',()=>{assert.throws(()=>validateNotice({...notice,result:{...result,observed_at:1001}},[pair]));assert.throws(()=>validateNotice({...notice,result:{...result,available_at:1001}},[pair]));assert.throws(()=>validateNotice({...notice,state:'read',read_at:999},[pair]));assert.throws(()=>validateWatch({...watch,status:'completed',completion_result:{...result,entity:{...result.entity,identity:'XETHZUSD'}}},[pair,'XETHZUSD']));assert.throws(()=>validateWatch({...watch,status:'completed',completion_result:{...result,value:1}},[pair]));});
test('failed relogin revokes old session before provider preparation',async()=>{const f=fixture();await f.login();f.setChain('0x1');await f.login();assert.equal(f.page.getSession(),null);assert.equal(f.get('createWatch').disabled,true);});
test('former provider cannot revoke replacement session after reselect',async()=>{let chosen;const f=fixture({page:{prepareProvider:async()=>chosen}});chosen={provider:f.provider,source:'injected_wallet'};await f.login();const oldListener=f.listeners.get('disconnect'),nextListeners=new Map();const next={request:f.provider.request,on:(event,fn)=>nextListeners.set(event,fn),removeListener:(event,fn)=>{if(nextListeners.get(event)===fn)nextListeners.delete(event);}};chosen={provider:next,source:'base_account'};await f.login();assert.equal(f.listeners.size,0);oldListener();assert.notEqual(f.page.getSession(),null);nextListeners.get('disconnect')();assert.equal(f.page.getSession(),null);});

test('disabled status survives wallet and later auth invalidation callbacks',()=>{const f=fixture({config:{enabled:false}});f.target.dispatchEvent(new Event('basedmoer:wallet'));f.auth.invalidate();assert.match(f.get('pageStatus').textContent,/research room is disabled/);assert.equal(f.get('login').disabled,true);assert.equal(f.calls.length,0);assert.equal(f.signs.length,0);});

test('page passes trusted pilot proof config without deriving audience from URL',()=>{const f=fixture({config:{enabled:false,loginProofVersion:'moer-staging-eoa-v1',audience:'https://test.example'}});assert.equal(f.sessionOptions().loginProofVersion,'moer-staging-eoa-v1');assert.equal(f.sessionOptions().audience,'https://test.example');assert.equal(f.sessionOptions().enabled,false);assert.equal(f.calls.length,0);});

test('enabled pilot page never falls back to legacy or missing proof config',()=>{for(const loginProofVersion of [undefined,'','legacy-production-v1','unknown'])assert.throws(()=>fixture({config:{loginProofVersion}}),/EXPLICIT_PILOT_PROOF_REQUIRED/);});

test('holder review renders source citations and supplied-record coverage',async()=>{const review=require('./review_fixtures.cjs');const f=fixture({client:{reviewRecords:async payload=>{assert.deepEqual(payload.records,review.references);return review.response();}}});await f.login();f.get('reviewReferences').value='scanner fixture_scanner\nradar_candidate fixture_radar';await f.get('reviewRecords').onclick();const text=node=>node.textContent+' '+node.children.map(text).join(' ');assert.match(text(f.get('reviewView')),/synthetic-browser:fixture_scanner/);assert.match(text(f.get('reviewView')),/only your 2 supplied records/);});
test('review disconnect clears references and fences old results',async()=>{const review=require('./review_fixtures.cjs');let release;const f=fixture({client:{reviewRecords:()=>new Promise(r=>release=r)}});await f.login();f.get('reviewReferences').value='scanner fixture_scanner\nradar_candidate fixture_radar';const p=f.get('reviewRecords').onclick();await new Promise(r=>setImmediate(r));f.target.dispatchEvent(new Event('basedmoer:wallet'));release(review.response());await p;assert.equal(f.get('reviewView').children.length,0);assert.equal(f.get('reviewReferences').value,'');});
test('lost current review session clears private results and disables review',async()=>{const f=fixture();await f.login();f.get('reviewReferences').value='scanner fixture_scanner';f.client.reviewRecords=async()=>{f.auth.invalidate();throw Object.assign(Error('denied'),{code:'AUTH_REQUIRED'});};await f.get('reviewRecords').onclick();assert.equal(f.get('reviewView').children.length,0);assert.equal(f.get('reviewReferences').value,'');assert.equal(f.get('reviewRecords').disabled,true);assert.equal(f.page.getSession(),null);});
test('invalid review references or mismatched response never render old coverage',async()=>{const review=require('./review_fixtures.cjs');let dispatched=0;const f=fixture({client:{reviewRecords:async()=>{dispatched++;const data=review.response();data.coverage.explained=0;return data;}}});await f.login();f.get('reviewReferences').value='scanner bad/id';f.get('reviewView').textContent='old';await f.get('reviewRecords').onclick();assert.equal(dispatched,0);assert.equal(f.get('reviewView').textContent,'');f.get('reviewReferences').value='scanner fixture_scanner\nradar_candidate fixture_radar';await f.get('reviewRecords').onclick();assert.equal(dispatched,1);assert.equal(f.get('reviewView').children.length,0);});
function recordListing(count=1){return {schema_version:'moer.record-list.v1',product:'scanner',records:Array.from({length:count},(_,index)=>({product:'scanner',record_id:'record_'+index,display_label:'BTC/USD',recorded_at:'2026-10-03T05:00:00Z',time_semantics:'recorded_row_time_not_provider_observation',evidence_state:'not_evaluated'})),requested_limit:20,scope:'approved_shared_holder_records',ordering:'recorded_row_time_desc_id_desc',completeness:'bounded_listing_not_market_coverage',limitations:['labels_are_not_native_identity','review_required_for_evidence']};}
test('recent authenticated records can populate manual review without evidence claims',async()=>{const f=fixture({client:{listRecords:async request=>{assert.deepEqual(request,{product:'scanner',limit:20});return recordListing();}}});await f.login();f.get('recordsProduct').value='scanner';await f.get('loadRecords').onclick();const label=f.get('recordChoices').children[0],input=label.children[0];assert.match(label.children[1].textContent,/not verified identity/);assert.match(f.get('recordListStatus').textContent,/Evidence not evaluated/);input.checked=true;await input.onchange();assert.equal(f.get('reviewReferences').value,'scanner record_0');input.checked=false;await input.onchange();assert.equal(f.get('reviewReferences').value,'');});
test('record selection preserves manual references and caps eight',async()=>{const f=fixture({client:{listRecords:async()=>recordListing(9)}});await f.login();f.get('recordsProduct').value='scanner';await f.get('loadRecords').onclick();f.get('reviewReferences').value='radar_candidate manual_record';for(const label of f.get('recordChoices').children){const input=label.children[0];input.checked=true;await input.onchange();}assert.equal(f.get('reviewReferences').value.split('\n').length,8);assert.match(f.get('reviewReferences').value,/radar_candidate manual_record/);assert.equal(f.get('recordChoices').children[8].children[0].checked,false);});
test('disconnect fences in-flight listing and old detached selectors',async()=>{let release;const f=fixture({client:{listRecords:()=>new Promise(r=>release=r)}});await f.login();f.get('recordsProduct').value='scanner';const p=f.get('loadRecords').onclick();await new Promise(r=>setImmediate(r));f.target.dispatchEvent(new Event('basedmoer:wallet'));release(recordListing());await p;assert.equal(f.get('recordChoices').children.length,0);assert.equal(f.get('reviewReferences').value,'');});
test('malformed or denied record listings leave no records and lost authority disables selector',async()=>{const f=fixture();await f.login();f.get('recordsProduct').value='scanner';f.client.listRecords=async()=>({...recordListing(),scope:'all_wallets'});await f.get('loadRecords').onclick();assert.equal(f.get('recordChoices').children.length,0);f.client.listRecords=async()=>{f.auth.invalidate();throw Object.assign(Error('denied'),{code:'AUTH_REQUIRED'});};await f.get('loadRecords').onclick();assert.equal(f.get('recordChoices').children.length,0);assert.equal(f.get('loadRecords').disabled,true);});
test('selectors from replaced listing cannot alter current manual references',async()=>{const f=fixture({client:{listRecords:async()=>recordListing()}});await f.login();f.get('recordsProduct').value='scanner';await f.get('loadRecords').onclick();const stale=f.get('recordChoices').children[0].children[0];await f.get('loadRecords').onclick();stale.checked=true;await stale.onchange();assert.equal(f.get('reviewReferences').value,'');});
