const {test}=require('node:test');const assert=require('node:assert/strict');
const {createClient}=require('../holder-intelligence-client.js');
const identifier='a'.repeat(32),wallet='0x'+'1'.repeat(40);
const stream=text=>new ReadableStream({start(c){c.enqueue(new TextEncoder().encode(text));c.close();}});
const response=(data={ok:true},status=200)=>({ok:status<400,status,headers:{get:()=> 'application/json'},body:stream(JSON.stringify(data))});
function fixture(extra={}){let current={wallet,token:'opaque-session',verified:true};const calls=[];const target=new EventTarget();const client=createClient({enabled:true,baseURL:'https://test.example',allowedOrigins:['https://test.example'],allowedPairs:['XXBTZUSD'],eventTarget:target,getSession:()=>current,fetch:async(...args)=>{calls.push(args);return response();},...extra});return {client,calls,target,setSession:s=>current=s};}
test('disabled by default and no startup request',async()=>{let count=0;const c=createClient({fetch:()=>count++});assert.equal(count,0);await assert.rejects(c.getWatch(identifier),{code:'DISABLED'});assert.equal(count,0);});
test('explicit trusted HTTPS origin only',()=>{for(const url of ['http://test.example','https://evil.example','https://a:b@test.example','https://test.example/path','https://test.example?x=1','https://test.example/#x'])assert.throws(()=>fixture({baseURL:url}));});
test('bearer sent only to configured endpoint without cookies or redirects',async()=>{const f=fixture();await f.client.getWatch(identifier);assert.equal(f.calls[0][0],'https://test.example/v1/intelligence/watches/'+identifier);const o=f.calls[0][1];assert.equal(o.headers.Authorization,'Bearer opaque-session');assert.equal(o.credentials,'omit');assert.equal(o.redirect,'error');assert.equal(o.referrerPolicy,'no-referrer');});
test('disconnect aborts and fences in-flight response',async()=>{let release,signal;const f=fixture({fetch:(_,o)=>{signal=o.signal;return new Promise(r=>release=r);}});const p=f.client.getWatch(identifier);f.target.dispatchEvent(new Event('basedmoer:wallet'));assert.equal(signal.aborted,true);release(response());await assert.rejects(p,{code:'STALE_CONTEXT'});});
test('wallet switch without event still fences',async()=>{let release;const f=fixture({fetch:()=>new Promise(r=>release=r)});const p=f.client.getWatch(identifier);f.setSession({wallet:'0x'+'2'.repeat(40),token:'other',verified:true});release(response());await assert.rejects(p,{code:'STALE_CONTEXT'});});
test('token rotation and disconnect during body read fence',async()=>{let release;const f=fixture({fetch:async()=>({...response(),body:{getReader:()=>({read:()=>new Promise(r=>release=r),cancel:()=>Promise.resolve(),releaseLock(){}})}})});const p=f.client.getWatch(identifier);await new Promise(r=>setImmediate(r));f.setSession({wallet,token:'new',verified:true});release({done:false,value:new TextEncoder().encode('{}')});await assert.rejects(p,{code:'STALE_CONTEXT'});});
test('current 401 and 403 invoke authority clear callback',async()=>{for(const status of [401,403]){let cleared;const f=fixture({fetch:async()=>response({},status),onUnauthorized:s=>cleared=s});await assert.rejects(f.client.getWatch(identifier),{code:'AUTH_REQUIRED',status});assert.equal(cleared,status);}});
test('stale unauthorized response cannot clear new wallet authority',async()=>{let release,cleared=false;const f=fixture({fetch:()=>new Promise(r=>release=r),onUnauthorized:()=>cleared=true});const p=f.client.getWatch(identifier);f.client.invalidate();release(response({},403));await assert.rejects(p,{code:'STALE_CONTEXT'});assert.equal(cleared,false);});
test('unverified session never dispatches',async()=>{const f=fixture();f.setSession({wallet,token:'x',verified:false});await assert.rejects(f.client.getWatch(identifier),{code:'AUTH_REQUIRED'});assert.equal(f.calls.length,0);});
test('narrow watch schema and native pair allowlist',async()=>{const f=fixture();const spec={entity:{kind:'market',network:'kraken',identity:'XXBTZUSD'},condition:{field:'price',operator:'gte',value:5,unit:'USD'}};await f.client.createWatch({request_key:'user-key',spec});assert.equal(JSON.parse(f.calls[0][1].body).spec.entity.identity,'XXBTZUSD');for(const identity of ['BTC/USD','BTCUSD','https://evil.example'])assert.throws(()=>f.client.createWatch({request_key:'key',spec:{...spec,entity:{...spec.entity,identity}}}));assert.throws(()=>f.client.createWatch({request_key:'key',wallet,spec}));assert.throws(()=>f.client.createWatch({request_key:'key',spec:{...spec,condition:{...spec.condition,value:NaN}}}));});
test('private IDs and cursor bounded; supported routes',async()=>{const f=fixture();assert.throws(()=>f.client.getWatch('../other'));assert.throws(()=>f.client.listNotifications({limit:101}));await f.client.cancelWatch(identifier);await f.client.acknowledgeNotification(identifier);await f.client.listNotifications({limit:1,beforeId:identifier});assert.equal(f.calls[0][1].method,'POST');assert.match(f.calls[2][0],/limit=1&before_id=/);});
test('redirect, malformed, oversized and network errors redacted',async()=>{for(const r of [{...response(),redirected:true},{...response(),body:stream('secret-not-json')},{...response(),body:stream('x'.repeat(1048577))}]){const f=fixture({fetch:async()=>r});await assert.rejects(f.client.getWatch(identifier),e=>!e.message.includes('secret'));}const f=fixture({fetch:async()=>{throw Error('bearer secret');}});await assert.rejects(f.client.getWatch(identifier),{code:'NETWORK_FAILED'});});
test('dispose blocks calls and unregisters event handler',async()=>{const f=fixture();f.client.dispose();await assert.rejects(f.client.getWatch(identifier),{code:'DISABLED'});assert.equal(f.calls.length,0);});

test('body cap counts actual UTF8 bytes and aborts oversized stream',async()=>{let signal;const f=fixture({fetch:async(_,o)=>{signal=o.signal;return {...response(),body:stream('é'.repeat(600000))};}});await assert.rejects(f.client.getWatch(identifier),{code:'RESPONSE_TOO_LARGE'});assert.equal(signal.aborted,true);});
test('deadline bounds hung transport and body',async()=>{for(const fetcher of [()=>new Promise(()=>{}),async()=>({...response(),body:{getReader:()=>({read:()=>new Promise(()=>{}),cancel:()=>Promise.resolve(),releaseLock(){}})}})]){const f=fixture({timeoutMs:10,fetch:fetcher});await assert.rejects(f.client.getWatch(identifier),{code:'TIMEOUT'});}});
