const {test}=require('node:test'),assert=require('node:assert/strict');
const {createSession}=require('../holder-intelligence-session.js');const {createClient}=require('../holder-intelligence-client.js');
const wallet='0x'+'1'.repeat(40),other='0x'+'2'.repeat(40),clock=Date.parse('2026-10-03T05:00:00Z'),signature='0x'+'a'.repeat(130),token='a'.repeat(64);
function reply(data,status=200){return {ok:status<400,status,headers:{get:()=> 'application/json'},body:new ReadableStream({start(c){c.enqueue(new TextEncoder().encode(JSON.stringify(data)));c.close();}})};}
function challenge(address=wallet){const expires_at=new Date(clock+600000).toISOString();return {success:true,wallet_address:address,holder_balance:1,expires_at,message:'Based Moer — Moe Agent Login\n\nWallet: '+address+'\nChain: Base (8453)\nNonce: '+'a'.repeat(32)+'\nExpires: '+expires_at+'\n\nSigning proves wallet ownership. It does not authorize a trade or transfer funds.'};}
function verified(address=wallet){return {success:true,session_token:token,expires_at:new Date(clock+86400000).toISOString(),holder_balance:1,account:{wallet_address:address}};}
function fixture(extra={}){let address=wallet,time=clock;const target=new EventTarget(),calls=[],signs=[];const session=createSession({enabled:true,baseURL:'https://test.example',allowedOrigins:['https://test.example'],getWallet:()=>address,now:()=>time,eventTarget:target,signChallenge:async(...a)=>{signs.push(a);return {signature};},fetch:async(url,opts)=>{calls.push([url,opts]);return reply(url.endsWith('/challenge')?challenge():verified());},...extra});return {session,target,calls,signs,wallet:v=>address=v,time:v=>time=v};}
test('default disabled no automatic auth or storage',async()=>{const s=createSession();assert.equal(s.getSession(),null);await assert.rejects(s.authenticate(),{code:'DISABLED'});});
test('explicit wallet events and trusted HTTPS origin required',()=>{for(const url of ['http://test.example','https://evil.example','https://x:y@test.example','https://test.example/path'])assert.throws(()=>fixture({baseURL:url}));assert.throws(()=>fixture({eventTarget:undefined}));});
test('successful challenge binds signature and verification wallet; token memory only',async()=>{const f=fixture();assert.equal(f.calls.length,0);assert.equal(f.session.getSession(),null);await f.session.authenticate();assert.deepEqual(f.session.getSession(),{wallet,token,verified:true});assert.deepEqual(f.signs[0],[challenge().message,wallet]);assert.deepEqual(JSON.parse(f.calls[1][1].body),{wallet_address:wallet,signature});assert.equal(f.calls[0][1].redirect,'error');assert.equal(f.calls[0][1].credentials,'omit');});
test('disconnect during challenge never signs or verifies',async()=>{let release;const f=fixture({fetch:()=>new Promise(r=>release=r)});const p=f.session.authenticate();f.target.dispatchEvent(new Event('basedmoer:wallet'));release(reply(challenge()));await assert.rejects(p,{code:'STALE_CONTEXT'});assert.equal(f.signs.length,0);assert.equal(f.session.getSession(),null);});
test('A B A event generations fence challenge',async()=>{let release;const f=fixture({fetch:()=>new Promise(r=>release=r)});const p=f.session.authenticate();f.wallet(other);f.target.dispatchEvent(new Event('basedmoer:wallet'));f.wallet(wallet);f.target.dispatchEvent(new Event('basedmoer:wallet'));release(reply(challenge()));await assert.rejects(p,{code:'STALE_CONTEXT'});assert.equal(f.session.getSession(),null);});
test('wallet switch while signing never verifies',async()=>{let release;const f=fixture({signChallenge:()=>new Promise(r=>release=r)});const p=f.session.authenticate();await new Promise(r=>setImmediate(r));f.wallet(other);release({signature});await assert.rejects(p,{code:'STALE_CONTEXT'});assert.equal(f.calls.length,1);});
test('stale verify never stores token or clears replacement',async()=>{let release,count=0;const f=fixture({fetch:async url=>{if(url.endsWith('/challenge'))return reply(challenge());if(++count===1)return new Promise(r=>release=r);return reply(verified());}});const first=f.session.authenticate();await new Promise(r=>setImmediate(r));await f.session.authenticate();release(reply({},403));await assert.rejects(first,{code:'STALE_CONTEXT'});assert.equal(f.session.getSession().token,token);});
test('challenge malformed wallet or arbitrary signing text rejected',async()=>{for(const c of [{...challenge(),wallet_address:other},{...challenge(),message:'approve spending'},{...challenge(),holder_balance:0},{...challenge(),expires_at:'tomorrow'}]){const f=fixture({fetch:async()=>reply(c)});await assert.rejects(f.session.authenticate());assert.equal(f.signs.length,0);}});
test('verified token requires holder and explicit account wallet binding',async()=>{for(const result of [{...verified(),account:{}},verified(other),{...verified(),holder_balance:0},{...verified(),session_token:'secret\nheader'},{...verified(),expires_at:new Date(clock-1).toISOString()}]){const f=fixture({fetch:async url=>reply(url.endsWith('/challenge')?challenge():result)});await assert.rejects(f.session.authenticate(),{code:'INVALID_RESPONSE'});assert.equal(f.session.getSession(),null);}});
test('session expires locally and disconnect clears authority',async()=>{const f=fixture();await f.session.authenticate();f.time(clock+86400000);assert.equal(f.session.getSession(),null);f.time(clock);await f.session.authenticate();f.target.dispatchEvent(new Event('basedmoer:wallet'));assert.equal(f.session.getSession(),null);});
test('deadline bounds hung signature; stale late signature cannot verify',async()=>{let release;const f=fixture({timeoutMs:10,signChallenge:()=>new Promise(r=>release=r)});await assert.rejects(f.session.authenticate(),{code:'TIMEOUT'});release({signature});await new Promise(r=>setImmediate(r));assert.equal(f.calls.length,1);assert.equal(f.session.getSession(),null);});
test('response stream byte cap and malformed UTF8 fail closed',async()=>{for(const bytes of [new Uint8Array(65537),new Uint8Array([255])]){const f=fixture({fetch:async()=>({...reply({}),body:new ReadableStream({start(c){c.enqueue(bytes);c.close();}})})});await assert.rejects(f.session.authenticate());assert.equal(f.signs.length,0);}});
test('coordinator integrates holder client with current bearer and rejection revocation',async()=>{const f=fixture();await f.session.authenticate();let bearer;const client=createClient({enabled:true,baseURL:'https://test.example',allowedOrigins:['https://test.example'],getSession:f.session.getSession,onUnauthorized:f.session.onUnauthorized,eventTarget:f.target,fetch:async(_,o)=>{bearer=o.headers.Authorization;return reply({},403);}});await assert.rejects(client.getWatch('a'.repeat(32)),{code:'AUTH_REQUIRED'});assert.equal(bearer,'Bearer '+token);assert.equal(f.session.getSession(),null);});
test('redacted transport failure never exposes server detail/signature/token',async()=>{const f=fixture({fetch:async()=>{throw new Error('private signature token');}});await assert.rejects(f.session.authenticate(),{code:'LOGIN_FAILED'});});
test('login deadline bounds hung headers and body readers',async()=>{for(const fetcher of [()=>new Promise(()=>{}),async()=>({...reply({}),body:{getReader:()=>({read:()=>new Promise(()=>{}),cancel:()=>Promise.resolve(),releaseLock(){}})}})]){const f=fixture({timeoutMs:10,fetch:fetcher});await assert.rejects(f.session.authenticate(),{code:'TIMEOUT'});assert.equal(f.session.getSession(),null);}});
test('expired challenge after signing never verifies',async()=>{const f=fixture({signChallenge:async()=>{f.time(clock+600001);return {signature};}});await assert.rejects(f.session.authenticate(),{code:'CHALLENGE_EXPIRED'});assert.equal(f.calls.length,1);});
test('redirected challenge cannot reach signing',async()=>{const f=fixture({fetch:async()=>({...reply(challenge()),redirected:true})});await assert.rejects(f.session.authenticate(),{code:'UNEXPECTED_REDIRECT'});assert.equal(f.signs.length,0);});
