const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function setup(){const sessions=new Map([['basedMoerWallet','0x'+'1'.repeat(40)],['moeAgentSession','old']]),elements=new Map(),listeners={},timers=[],pending=[],buttons=[];
const sessionStorage={getItem:k=>sessions.get(k)||null,setItem:(k,v)=>sessions.set(k,v),removeItem:k=>sessions.delete(k)};
const get=id=>{if(id==='moerXpSection')return null;if(!elements.has(id))elements.set(id,{textContent:'',style:{},hidden:false,innerHTML:''});return elements.get(id)};
const passport={querySelectorAll:()=>[],appendChild(){},classList:{remove(){},add(){}}};
const window={addEventListener:(name,fn)=>listeners[name]=fn};window.MoerAcademyState=require('../academy-state.js').create({getItem:()=>null,setItem(){}},sessionStorage);
const context={window,sessionStorage,localStorage:{getItem:()=>null,setItem(){},removeItem(){}},location:{hostname:'basedmoer.com',pathname:'/profile/',search:''},URLSearchParams,document:{readyState:'complete',getElementById:get,querySelector:s=>s==='.passport'?passport:null,querySelectorAll:()=>buttons,createElement:()=>({}),addEventListener(){}},setTimeout:fn=>timers.push(fn),fetch:(url,opts)=>new Promise(resolve=>pending.push({url,opts,resolve})),ethereum:{request:async()=> '0xsig'},console};window.ethereum=context.ethereum;
for(const id of ['profileCompleted','profileAverage','flipPlayed','flipWins','flipRate','flipStreak'])context[id]=get(id);
vm.runInNewContext(fs.readFileSync(require('node:path').join(__dirname,'../progression.js'),'utf8'),context);
const switchTo=()=>{sessions.set('basedMoerWallet','0x'+'2'.repeat(40));sessions.set('moeAgentSession','new');listeners['basedmoer:wallet']()};
const respond=(i,data,ok=true)=>pending[i].resolve({ok,status:ok?200:401,json:async()=>data});return {sessions,get,timers,pending,switchTo,respond,buttons};}
test('stale Passport error cannot clear new session',async()=>{const f=setup();const load=f.timers[0]();f.switchTo();f.respond(0,{detail:'session expired'},false);await load;assert.equal(f.sessions.get('moeAgentSession'),'new')});
test('wallet switch while auth challenge pending never signs/verifies or replaces session',async()=>{const f=setup();f.sessions.delete('moeAgentSession');const auth=f.get('moerXpAuth').onclick();f.switchTo();f.respond(0,{wallet_address:'0x'+'1'.repeat(40),message:'login'});await auth;assert.equal(f.pending.length,1);assert.equal(f.sessions.get('moeAgentSession'),'new')});
test('stale daily claim does not render old progress and wallet event clears display',async()=>{const f=setup();f.get('moerLifetimeXp').textContent='500 XP';const claim=f.get('moerXpDaily').onclick();f.switchTo();assert.equal(f.get('moerLifetimeXp').textContent,'—');assert.equal(f.get('moerXpDaily').hidden,true);f.respond(0,{message:'old',progression:{lifetime_xp:999,level:3,catalog:[]}});await claim;assert.equal(f.get('moerLifetimeXp').textContent,'—')});

test('wallet switch during verify cannot store obsolete authentication token',async()=>{const f=setup();f.sessions.delete('moeAgentSession');const auth=f.get('moerXpAuth').onclick();f.respond(0,{wallet_address:'0x'+'1'.repeat(40),message:'login'});await new Promise(r=>setImmediate(r));assert.equal(f.pending.length,2);f.switchTo();f.respond(1,{session_token:'obsolete'});await auth;assert.equal(f.sessions.get('moeAgentSession'),'new')});
test('stale equip response cannot apply old cosmetics',async()=>{const f=setup(),button={dataset:{equip:'frame_cyan_signal'}};f.buttons.push(button);const load=f.timers[0]();f.respond(0,{progression:{lifetime_xp:100,level:1,catalog:[]}});await new Promise(r=>setImmediate(r));const equip=button.onclick();f.switchTo();f.respond(2,{progression:{lifetime_xp:999,level:3,catalog:[],equipped:{ship:'old'}}});await equip;assert.equal(f.get('moerLifetimeXp').textContent,'—');f.respond(1,{progress:{scores:{}}});await load;assert.equal(f.get('moerLifetimeXp').textContent,'—')});
