const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
function harness(){let address='0x'+'1'.repeat(40);const values=new Map(),events=[],rpc=[],alerts=[],content={hidden:true},lock={hidden:false};const storage={getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)};const document={getElementById:()=>null,querySelectorAll:s=>s==='[data-holder-content]'?[content]:s==='[data-holder-lock]'?[lock]:[],addEventListener(){}};const ethereum={request:async({method})=>method==='eth_chainId'?'0x2105':[address]};const window={ethereum};const context={window,document,sessionStorage:storage,localStorage:storage,location:{pathname:'/',hostname:'basedmoer.com'},console:{warn(){},error(){}},fetch:()=>new Promise(resolve=>rpc.push(resolve)),dispatchEvent:e=>events.push(e.detail),CustomEvent:class{constructor(name,{detail}){this.detail=detail}},alert:t=>alerts.push(t)};
let source=fs.readFileSync(path.join(__dirname,'../shared.js'),'utf8');source=source.replace(/\}\)\(\);\s*$/, 'globalThis.testConnection={connectWallet,disconnectWallet,restoreWallet};})();');vm.runInNewContext(source,context);
return {api:context.testConnection,values,events,rpc,content,alerts,setAddress:a=>address=a,resolve:(i,result='0x1')=>rpc[i]({ok:true,json:async()=>({result})})};}
const flush=()=>new Promise(r=>setImmediate(r));
test('disconnect during holder lookup fences obsolete connection',async()=>{const f=harness();const pending=f.api.connectWallet();await flush();assert.equal(f.rpc.length,1);f.api.disconnectWallet();f.resolve(0);await pending;assert.equal(f.values.has('basedMoerWallet'),false);assert.equal(f.content.hidden,true);assert.equal(f.events.at(-1).wallet,null);assert.equal(f.alerts.length,0)});
test('overlapping connection completes newest wallet only',async()=>{const f=harness();const old=f.api.connectWallet();await flush();f.setAddress('0x'+'2'.repeat(40));const latest=f.api.connectWallet();await flush();f.resolve(1);await latest;f.values.set('moeAgentSession','new-token');f.resolve(0,'0x0');await old;assert.equal(f.values.get('basedMoerWallet'),'0x'+'2'.repeat(40));assert.equal(f.values.get('moeAgentSession'),'new-token');assert.equal(f.values.get('basedMoerHolder'),'1');assert.equal(f.content.hidden,false);assert.equal(f.alerts.length,0)});
test('disconnect fences pending restore',async()=>{const f=harness();f.values.set('basedMoerWallet','0x'+'1'.repeat(40));f.values.set('basedMoerWalletSource','injected_wallet');const pending=f.api.restoreWallet();await flush();assert.equal(f.rpc.length,1);f.api.disconnectWallet();f.resolve(0);await pending;assert.equal(f.values.has('basedMoerWallet'),false);assert.equal(f.values.has('basedMoerHolder'),false);assert.equal(f.content.hidden,true)});
test('new connection supersedes restore and clears previous token immediately',async()=>{const f=harness();f.values.set('basedMoerWallet','0x'+'1'.repeat(40));f.values.set('basedMoerWalletSource','injected_wallet');f.values.set('moeAgentSession','old-token');const old=f.api.restoreWallet();await flush();f.setAddress('0x'+'2'.repeat(40));const latest=f.api.connectWallet();assert.equal(f.values.has('moeAgentSession'),false);await flush();f.resolve(1);await latest;f.resolve(0);await old;assert.equal(f.values.get('basedMoerWallet'),'0x'+'2'.repeat(40))});
