(function(){
const API='https://moe-ai-production.up.railway.app';
const preview=new URLSearchParams(location.search).get('preview')==='holder';
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),W=canvas.width,H=canvas.height,keys={};ctx.imageSmoothingEnabled=false;
const shipImages={main:new Image(),red:new Image(),cyan:new Image()};let originalShipReady=false;shipImages.main.onload=()=>originalShipReady=true;shipImages.main.onerror=()=>originalShipReady=false;shipImages.main.src='/assets/spaceship-main.png';shipImages.red.src='/assets/spaceship-red.png';shipImages.cyan.src='/assets/spaceship-cyan.png';
let running=false,score=0,lives=3,startAt=0,runToken='',last=0,enemyTimer=0,shotTimer=0,powerTimer=0,bossSpawned=false,bossKilled=false,rapid=0,spread=0,combo=0,comboTimer=0,screenShake=0;
let player={x:72,y:H/2,w:64,h:46,speed:270,invuln:0},shots=[],enemyShots=[],enemies=[],particles=[],stars=[],powers=[],asteroids=[];
const $=id=>document.getElementById(id),session=()=>sessionStorage.getItem('moeAgentSession')||'',wallet=()=>sessionStorage.getItem('basedMoerWallet')||'';
for(let i=0;i<120;i++)stars.push({x:Math.random()*W,y:Math.random()*H,s:1+Math.floor(Math.random()*3),v:18+Math.random()*92,c:Math.random()<.12?'#a978ff':Math.random()<.2?'#55dfff':'#7587a9'});
for(let i=0;i<16;i++)asteroids.push({x:Math.random()*W,y:40+Math.random()*(H-90),s:5+Math.floor(Math.random()*13),v:12+Math.random()*24});
async function req(path,opts={}){const t=session(),r=await fetch(API+path,{...opts,headers:{'Content-Type':'application/json',...(t?{Authorization:'Bearer '+t}:{}),...(opts.headers||{})}}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.detail||j.error||('HTTP '+r.status));return j}
async function authenticate(){const w=wallet();if(!w||!window.ethereum)throw new Error('Connect your holder wallet first.');const c=await req('/v1/agent/auth/challenge',{method:'POST',body:JSON.stringify({wallet_address:w})}),sig=await ethereum.request({method:'personal_sign',params:[c.message,w]}),v=await req('/v1/agent/auth/verify',{method:'POST',body:JSON.stringify({wallet_address:w,signature:sig})});sessionStorage.setItem('moeAgentSession',v.session_token)}
function rect(x,y,w,h,f){ctx.fillStyle=f;ctx.fillRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h))}
function pixelText(text,x,y,size=10,color='#aee8ff',align='left'){ctx.save();ctx.font=`900 ${size}px monospace`;ctx.textAlign=align;ctx.fillStyle='#02040a';ctx.fillText(text,x+1,y+1);ctx.fillStyle=color;ctx.fillText(text,x,y);ctx.restore()}
function drawFallbackShip(x,y){const skin=localStorage.getItem('moerArcadeShip')||'';let a='#3153d7',b='#6f91ff',c='#bfeeff',d='#7d2aa8';if(skin==='ship_void_runner'){a='#411285';b='#8b49e8';c='#efd4ff';d='#f04bc8'}else if(skin==='ship_moe_scout'){a='#116b9a';b='#45d9e0';c='#d6ffff';d='#5075ff'}
rect(x+20,y+2,20,6,c);rect(x+14,y+8,32,8,b);rect(x+8,y+16,44,12,a);rect(x+2,y+24,56,8,b);rect(x+15,y+32,30,8,a);rect(x+25,y+40,10,5,c);rect(x+5,y+10,8,8,b);rect(x+47,y+10,8,8,b);rect(x-3,y+27,8,5,d);rect(x+55,y+27,8,5,d);rect(x+24,y+15,12,16,'#12182a');rect(x+27,y+18,6,10,'#84269b');rect(x+14,y+39,8,5,'#63efff');rect(x+38,y+39,8,5,'#63efff')}
function drawPlayer(){ctx.save();if(player.invuln>0&&Math.floor(player.invuln*12)%2===0)ctx.globalAlpha=.35;const skin=localStorage.getItem('moerArcadeShip')||'';const art=skin==='ship_void_runner'?shipImages.red:skin==='ship_moe_scout'?shipImages.cyan:shipImages.main;if(originalShipReady&&art.complete&&art.naturalWidth){ctx.imageSmoothingEnabled=false;ctx.drawImage(art,Math.round(player.x-10),Math.round(player.y-13),84,84)}else drawFallbackShip(player.x,player.y);if(rapid>0||spread>0){ctx.globalAlpha=.55;ctx.strokeStyle=rapid>0?'#5affd3':'#b98cff';ctx.lineWidth=2;ctx.strokeRect(Math.round(player.x-5),Math.round(player.y-5),74,56)}ctx.restore()}
function drawScout(e){const x=e.x,y=e.y;rect(x+8,y,18,5,'#ffd478');rect(x+3,y+5,28,6,'#e26b44');rect(x,y+11,34,9,'#923d48');rect(x+7,y+20,20,6,'#57243e');rect(x-5,y+12,7,5,'#ffad5a');rect(x+32,y+12,7,5,'#ffec9a');rect(x+12,y+9,10,8,'#19132c');rect(x+15,y+11,4,4,'#ff405f')}
function drawInterceptor(e){const x=e.x,y=e.y;rect(x+10,y,20,5,'#ff8dc5');rect(x+4,y+5,32,7,'#c3397e');rect(x,y+12,40,10,'#6d2369');rect(x+6,y+22,28,7,'#35124e');rect(x-7,y+14,8,5,'#a862ff');rect(x+39,y+14,8,5,'#87f5ff');rect(x+13,y+8,14,12,'#130e22');rect(x+17,y+11,6,6,'#57e8ff')}
function drawMine(e){const x=e.x,y=e.y;rect(x+8,y,18,18,'#7d3153');rect(x+12,y+4,10,10,'#ff4d78');rect(x+15,y+7,4,4,'#fff0b0');rect(x+14,y-7,6,8,'#b44564');rect(x+14,y+25,6,8,'#b44564');rect(x-7,y+7,8,6,'#b44564');rect(x+31,y+7,8,6,'#b44564')}
function drawBoss(e){const x=e.x,y=e.y;rect(x+28,y,50,8,'#d8b2ff');rect(x+16,y+8,74,12,'#884bc2');rect(x+6,y+20,94,22,'#4b247d');rect(x,y+42,106,22,'#29164f');rect(x+14,y+64,78,14,'#542a82');rect(x-12,y+30,18,26,'#a73c9d');rect(x+100,y+30,18,26,'#4be8ff');rect(x+28,y+25,18,18,'#170b27');rect(x+62,y+25,18,18,'#170b27');rect(x+33,y+30,8,8,'#ff4c88');rect(x+67,y+30,8,8,'#5ff5ff');rect(x+45,y+45,18,13,'#12081d');rect(x+49,y+48,10,5,'#f0b5ff');for(let i=0;i<5;i++){rect(x+10+i*20,y+70,9,6,i%2?'#67edff':'#d95dff')}}
function drawEnemy(e){if(e.type===4)drawBoss(e);else if(e.type===3)drawMine(e);else if(e.type===2)drawInterceptor(e);else drawScout(e)}
function explosion(x,y,n=12,palette=['#fff3a0','#ff9f43','#ff4e74','#7d4cff']){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*260,vy:(Math.random()-.5)*260,life:.35+Math.random()*.8,size:2+Math.floor(Math.random()*5),c:palette[Math.floor(Math.random()*palette.length)]});screenShake=Math.min(8,screenShake+n/7)}
function hit(a,b,pad=0){return a.x+pad<b.x+b.w-pad&&a.x+a.w-pad>b.x+pad&&a.y+pad<b.y+b.h-pad&&a.y+a.h-pad>b.y+pad}
function reset(){score=0;lives=3;shots=[];enemyShots=[];enemies=[];particles=[];powers=[];player.x=72;player.y=H/2;player.invuln=0;startAt=performance.now();last=startAt;enemyTimer=0;shotTimer=0;powerTimer=7;bossSpawned=false;bossKilled=false;rapid=0;spread=0;combo=0;comboTimer=0;screenShake=0;updateHud()}
async function start(){try{if(preview){runToken='preview';reset();running=true;$('overlay').hidden=true;$('status').textContent='CREATOR PREVIEW • FULL PRACTICE • NO XP SAVED';requestAnimationFrame(loop);return}$('status').textContent='Preparing verified run…';if(!session())await authenticate();const r=await req('/v1/progression/arcade/start',{method:'POST',body:'{}'});runToken=r.run_token;reset();running=true;$('overlay').hidden=true;$('status').textContent='SECTOR 01 ACTIVE • FIRST CONTACT';requestAnimationFrame(loop)}catch(e){$('status').textContent=e.message;$('overlayTitle').textContent='AUTH REQUIRED';$('overlayText').textContent=e.message;$('overlay').hidden=false}}
function shoot(){if(shotTimer>0)return;const base={x:player.x+57,y:player.y+21,w:13,h:3,v:590,damage:rapid>0?2:1};shots.push({...base,vy:0});if(spread>0){shots.push({...base,y:base.y-5,vy:-70},{...base,y:base.y+5,vy:70})}shotTimer=rapid>0?.075:.15}
function spawn(type){if(type===4){enemies.push({x:W+20,y:H/2-48,w:108,h:80,v:38,type:4,hp:38,maxHp:38,fire:1.1,phase:0});return}if(!type){const r=Math.random();type=r<.16?3:r<.38?2:1}const cfg=type===3?{w:34,h:34,v:85,hp:3}:type===2?{w:42,h:30,v:175,hp:2}:{w:38,h:27,v:205,hp:1};enemies.push({x:W+35,y:30+Math.random()*(H-90),type,...cfg,fire:.8+Math.random()*1.8,phase:Math.random()*6})}
function spawnPower(){const r=Math.random(),type=r<.42?'rapid':r<.75?'shield':'spread';powers.push({x:W+20,y:42+Math.random()*(H-100),w:20,h:20,v:100,type})}
function fireEnemy(e){if(e.type===4){for(let i=-2;i<=2;i++)enemyShots.push({x:e.x+4,y:e.y+40,w:8,h:4,vx:-180,vy:i*42,c:i%2?'#ff62c0':'#7fe8ff'});return}enemyShots.push({x:e.x,y:e.y+e.h/2,w:7,h:3,vx:-180-Math.random()*60,vy:(Math.random()-.5)*35,c:e.type===2?'#e26cff':'#ff755f'})}
function killEnemy(e){e.dead=true;combo=Math.min(9,combo+1);comboTimer=2.4;const base=e.type===4?1600:e.type===3?240:e.type===2?200:120;score+=base+combo*10;explosion(e.x+e.w/2,e.y+e.h/2,e.type===4?65:e.type===3?20:14);if(e.type===4){bossKilled=true;$('status').textContent='SECTOR BOSS DESTROYED • SURVIVE EXTRACTION'}}
function damagePlayer(){if(player.invuln>0)return;lives--;player.invuln=1.25;combo=0;comboTimer=0;explosion(player.x+32,player.y+23,24,['#d5ffff','#5de7ff','#4667ff','#9b4fff']);updateHud();if(lives<=0)finish()}
function updateHud(){if($('score'))$('score').textContent=score.toLocaleString();if($('lives'))$('lives').textContent=lives;if($('runXp'))$('runXp').textContent=preview?'DEMO':Math.min(25,Math.floor(score/1000));if($('weapon'))$('weapon').textContent=rapid>0?'RAPID':spread>0?'SPREAD':'PULSE';if($('combo'))$('combo').textContent='x'+Math.max(1,combo);const boss=enemies.find(e=>e.type===4&&!e.dead);if($('bossHp')){$('bossHp').textContent=boss?`${Math.max(0,boss.hp)} / ${boss.maxHp}`:bossKilled?'DOWN':'—'}}}
function update(dt){stars.forEach(s=>{s.x-=s.v*dt;if(s.x<0){s.x=W;s.y=Math.random()*H}});asteroids.forEach(a=>{a.x-=a.v*dt;if(a.x<-20){a.x=W+Math.random()*180;a.y=40+Math.random()*(H-90)}});const dx=(keys.ArrowRight||keys.KeyD?1:0)-(keys.ArrowLeft||keys.KeyA?1:0),dy=(keys.ArrowDown||keys.KeyS?1:0)-(keys.ArrowUp||keys.KeyW?1:0);player.x=Math.max(12,Math.min(W-86,player.x+dx*player.speed*dt));player.y=Math.max(12,Math.min(H-62,player.y+dy*player.speed*dt));if(keys.Space)shoot();shotTimer=Math.max(0,shotTimer-dt);rapid=Math.max(0,rapid-dt);spread=Math.max(0,spread-dt);player.invuln=Math.max(0,player.invuln-dt);comboTimer=Math.max(0,comboTimer-dt);if(comboTimer<=0)combo=0;screenShake=Math.max(0,screenShake-20*dt);
const elapsed=(performance.now()-startAt)/1000;enemyTimer-=dt;if(enemyTimer<=0&&!bossSpawned){spawn();enemyTimer=Math.max(.34,.9-elapsed/110)}powerTimer-=dt;if(powerTimer<=0){spawnPower();powerTimer=8+Math.random()*5}if(elapsed>=43&&!bossSpawned){bossSpawned=true;spawn(4);$('status').textContent='WARNING • MOERVERSE WARDEN APPROACHING'}
shots.forEach(s=>{s.x+=s.v*dt;s.y+=s.vy*dt});shots=shots.filter(s=>s.x<W+30&&s.y>-20&&s.y<H+20);enemyShots.forEach(s=>{s.x+=s.vx*dt;s.y+=s.vy*dt});enemyShots=enemyShots.filter(s=>s.x>-30&&s.y>-30&&s.y<H+30);enemies.forEach(e=>{if(e.type===4){if(e.x>W-150)e.x-=e.v*dt;e.phase+=dt;e.y=H/2-48+Math.sin(e.phase*1.6)*78}else{e.x-=e.v*dt;e.y+=Math.sin((elapsed+e.phase)*2.2)*(e.type===3?18:7)*dt}e.fire-=dt;if(e.fire<=0&&e.x<W-30){fireEnemy(e);e.fire=e.type===4?.8:1.2+Math.random()*2}});powers.forEach(p=>p.x-=p.v*dt);particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.985;p.vy*=.985;p.life-=dt});particles=particles.filter(p=>p.life>0);
for(const s of shots){for(const e of enemies){if(!s.dead&&!e.dead&&hit(s,e,2)){s.dead=true;e.hp-=s.damage;explosion(s.x,s.y,3,['#fff','#63edff','#b78cff']);if(e.hp<=0)killEnemy(e)}}}shots=shots.filter(s=>!s.dead);
for(const p of powers){if(hit(player,p,2)){p.dead=true;if(p.type==='rapid'){rapid=8;$('status').textContent='RAPID PULSE ONLINE • 8 SEC'}else if(p.type==='spread'){spread=8;$('status').textContent='TRI-BEAM ONLINE • 8 SEC'}else{lives=Math.min(5,lives+1);$('status').textContent='SHIELD CELL ACQUIRED'}explosion(p.x,p.y,10)}}powers=powers.filter(p=>!p.dead&&p.x>-30);
for(const s of enemyShots){if(!s.dead&&hit(player,s,8)){s.dead=true;damagePlayer()}}enemyShots=enemyShots.filter(s=>!s.dead);
for(const e of enemies){if(e.dead)continue;if(hit(player,e,e.type===4?12:5)){if(e.type!==4)e.dead=true;damagePlayer()}else if(e.x<-140)e.dead=true}enemies=enemies.filter(e=>!e.dead);
const remain=Math.max(0,60-Math.floor(elapsed));$('time').textContent=remain;updateHud();if(elapsed>=60)finish()}
function drawBackground(){rect(0,0,W,H,'#020510');for(const s of stars)rect(s.x,s.y,s.s,s.s,s.c);ctx.globalAlpha=.24;rect(0,H-86,W,86,'#0b1232');for(let x=0;x<W;x+=16){const h=12+((x*13)%38);rect(x,H-h,12,h,'#111c4c');if(x%64===0)rect(x+3,H-h+5,3,3,'#41d8ff')}ctx.globalAlpha=1;ctx.save();ctx.globalAlpha=.18;ctx.fillStyle='#5b2e9c';ctx.beginPath();ctx.arc(W-90,88,58,0,Math.PI*2);ctx.fill();ctx.fillStyle='#1c7eb2';ctx.beginPath();ctx.arc(W-105,73,45,0,Math.PI*2);ctx.fill();ctx.restore();for(const a of asteroids){rect(a.x,a.y,a.s,a.s,'#2d3246');rect(a.x+2,a.y+2,a.s-4,a.s-4,'#454a61');if(a.s>10)rect(a.x+4,a.y+3,3,3,'#181c2a')}ctx.globalAlpha=.16;ctx.strokeStyle='#38bfff';for(let y=40;y<H;y+=64){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}ctx.globalAlpha=1}
function drawPower(p){const c=p.type==='rapid'?'#54ffd0':p.type==='spread'?'#c078ff':'#5ca5ff';rect(p.x,p.y,20,20,'#101a31');rect(p.x+2,p.y+2,16,16,c);rect(p.x+6,p.y+6,8,8,'#fff');if(p.type==='rapid'){rect(p.x+9,p.y+2,2,16,'#0d6858')}else if(p.type==='spread'){rect(p.x+4,p.y+9,12,2,'#532081')}else{rect(p.x+9,p.y+4,2,12,'#1a4b95');rect(p.x+4,p.y+9,12,2,'#1a4b95')}}
function draw(){ctx.save();if(screenShake>0)ctx.translate((Math.random()-.5)*screenShake,(Math.random()-.5)*screenShake);drawBackground();drawPlayer();shots.forEach(s=>{rect(s.x,s.y,s.w,s.h,rapid>0?'#64ffd5':spread>0?'#bd7dff':'#63e8ff');rect(s.x+s.w,s.y+1,4,1,'#fff')});enemyShots.forEach(s=>{rect(s.x,s.y,s.w,s.h,s.c);rect(s.x-3,s.y+1,3,1,'#fff')});enemies.forEach(drawEnemy);powers.forEach(drawPower);particles.forEach(p=>rect(p.x,p.y,p.size,p.size,p.c));ctx.restore();const boss=enemies.find(e=>e.type===4&&!e.dead);if(boss){rect(190,12,340,13,'#17112b');rect(194,16,332*(boss.hp/boss.maxHp),5,'#c64cff');pixelText('MOERVERSE WARDEN',360,37,9,'#e4c3ff','center')}if(combo>1)pixelText(`COMBO x${combo}`,W-18,H-18,11,'#63ffd7','right')}
async function finish(){if(!running)return;running=false;draw();const duration=Math.max(1,Math.round((performance.now()-startAt)/1000));$('overlay').hidden=false;$('overlayTitle').textContent=lives<=0?'SHIP LOST':'RUN COMPLETE';$('startBtn').textContent='PLAY AGAIN';if(preview){$('overlayText').textContent=`Creator preview score ${score.toLocaleString()} • ${bossKilled?'boss defeated':'boss survived'} • practice only, no XP saved.`;$('status').textContent='PREVIEW RUN COMPLETE';return}$('overlayText').textContent=`Score ${score.toLocaleString()} • validating MOER XP…`;try{const r=await req('/v1/progression/arcade/submit',{method:'POST',body:JSON.stringify({run_token:runToken,score,duration_seconds:duration})});$('runXp').textContent=r.xp_awarded;$('overlayText').textContent=`Score ${score.toLocaleString()} • +${r.xp_awarded} MOER XP • ${r.daily_arcade_xp_remaining} daily Arcade XP remaining.`;$('status').textContent='RUN VALIDATED • PASSPORT SYNCED'}catch(e){$('overlayText').textContent=`Score ${score.toLocaleString()} • XP validation failed: ${e.message}`;$('status').textContent='NO XP AWARDED • VALIDATION FAILED'}}
function loop(t){if(!running)return;const dt=Math.min(.033,(t-last)/1000);last=t;update(dt);draw();if(running)requestAnimationFrame(loop)}
window.addEventListener('keydown',e=>{keys[e.code]=true;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault()});window.addEventListener('keyup',e=>keys[e.code]=false);document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key;b.addEventListener('pointerdown',e=>{e.preventDefault();keys[k]=true});['pointerup','pointercancel','pointerleave'].forEach(ev=>b.addEventListener(ev,()=>keys[k]=false))});if(preview){$('overlayTitle').textContent='CREATOR TEST MODE';$('overlayText').textContent='Full Sector 01 practice is enabled without an NFT. No XP or server progression is written.';$('startBtn').textContent='START PRACTICE RUN'}$('startBtn').addEventListener('click',start);draw();
})();