(function(){
const canvas=document.getElementById('eventGame'),ctx=canvas.getContext('2d'),W=canvas.width,H=canvas.height,keys={};ctx.imageSmoothingEnabled=false;
const $=id=>document.getElementById(id),ship=new Image();ship.src='/assets/spaceship-main.png';
let running=false,startAt=0,last=0,score=0,lives=5,shotCd=0,enemyCd=0,powerCd=7,rapid=0,spread=0,combo=0,comboTimer=0,bossSpawned=false,bossKilled=false,shake=0;
let player={x:72,y:H/2,w:64,h:46,speed:275,inv:0},shots=[],enemyShots=[],enemies=[],powers=[],particles=[],stars=[],rocks=[];
for(let i=0;i<125;i++)stars.push({x:Math.random()*W,y:Math.random()*H,s:1+Math.floor(Math.random()*3),v:20+Math.random()*95,c:Math.random()<.12?'#ad7cff':Math.random()<.2?'#61e2ff':'#7587a9'});
for(let i=0;i<18;i++)rocks.push({x:Math.random()*W,y:40+Math.random()*(H-90),s:5+Math.floor(Math.random()*14),v:10+Math.random()*28});
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h))}
function hit(a,b,p=0){return a.x+p<b.x+b.w-p&&a.x+a.w-p>b.x+p&&a.y+p<b.y+b.h-p&&a.y+a.h-p>b.y+p}
function burst(x,y,n=14){const pal=['#fff5b0','#ff9d48','#ff4e80','#784cff','#65eaff'];for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*280,vy:(Math.random()-.5)*280,life:.35+Math.random()*.8,s:2+Math.floor(Math.random()*5),c:pal[Math.floor(Math.random()*pal.length)]});shake=Math.min(9,shake+n/7)}
function reset(){score=0;lives=5;shots=[];enemyShots=[];enemies=[];powers=[];particles=[];player.x=72;player.y=H/2;player.inv=0;shotCd=0;enemyCd=.4;powerCd=7;rapid=0;spread=0;combo=0;comboTimer=0;bossSpawned=false;bossKilled=false;shake=0;startAt=performance.now();last=startAt;updateHud(0)}
function phase(elapsed){if(elapsed<25)return'CONTACT';if(elapsed<55)return'ESCALATION';if(!bossKilled)return'WARDEN';return'EXTRACTION'}
function spawnEnemy(type){if(type==='boss'){enemies.push({type:'boss',x:W+20,y:H/2-50,w:112,h:84,v:38,hp:58,max:58,fire:.8,phase:0});bossSpawned=true;return}const r=Math.random();if(!type)type=r<.18?'mine':r<.44?'interceptor':'scout';const cfg=type==='mine'?{w:34,h:34,v:90,hp:3}:type==='interceptor'?{w:42,h:30,v:180,hp:2}:{w:38,h:27,v:210,hp:1};enemies.push({type,x:W+30,y:30+Math.random()*(H-90),fire:.8+Math.random()*1.8,phase:Math.random()*6,...cfg})}
function spawnPower(){const r=Math.random(),type=r<.42?'rapid':r<.76?'shield':'spread';powers.push({type,x:W+20,y:45+Math.random()*(H-105),w:20,h:20,v:105})}
function shoot(){if(shotCd>0)return;const s={x:player.x+57,y:player.y+21,w:13,h:3,vx:600,vy:0,d:rapid>0?2:1};shots.push(s);if(spread>0)shots.push({...s,y:s.y-6,vy:-75},{...s,y:s.y+6,vy:75});shotCd=rapid>0?.075:.15}
function enemyFire(e){if(e.type==='boss'){for(let i=-2;i<=2;i++)enemyShots.push({x:e.x+4,y:e.y+41,w:8,h:4,vx:-190,vy:i*44,c:i%2?'#ff65c4':'#75edff'});return}enemyShots.push({x:e.x,y:e.y+e.h/2,w:7,h:3,vx:-190-Math.random()*55,vy:(Math.random()-.5)*40,c:e.type==='interceptor'?'#d96eff':'#ff765f'})}
function damage(){if(player.inv>0)return;lives--;player.inv=1.25;combo=0;comboTimer=0;burst(player.x+32,player.y+23,24);if(lives<=0)finish(false)}
function kill(e){e.dead=true;combo=Math.min(9,combo+1);comboTimer=2.4;score+=(e.type==='boss'?2400:e.type==='mine'?260:e.type==='interceptor'?210:120)+combo*10;burst(e.x+e.w/2,e.y+e.h/2,e.type==='boss'?75:15);if(e.type==='boss'){bossKilled=true;$('eventStatus').textContent='WARDEN DESTROYED • EXTRACTION WINDOW OPEN'}}
function updateHud(elapsed){$('demoScore').textContent=score.toLocaleString();$('demoLives').textContent=lives;$('demoTime').textContent=Math.max(0,120-Math.floor(elapsed));$('demoPhase').textContent=phase(elapsed);$('demoWeapon').textContent=rapid>0?'RAPID':spread>0?'TRI-BEAM':'PULSE';$('demoCombo').textContent='x'+Math.max(1,combo);const b=enemies.find(e=>e.type==='boss'&&!e.dead);$('demoBoss').textContent=b?`${Math.max(0,b.hp)}/${b.max}`:bossKilled?'DOWN':bossSpawned?'LOST':'—'}
function update(dt){const elapsed=(performance.now()-startAt)/1000;stars.forEach(s=>{s.x-=s.v*dt;if(s.x<0){s.x=W;s.y=Math.random()*H}});rocks.forEach(r=>{r.x-=r.v*dt;if(r.x<-20){r.x=W+Math.random()*180;r.y=40+Math.random()*(H-90)}});const dx=(keys.ArrowRight||keys.KeyD?1:0)-(keys.ArrowLeft||keys.KeyA?1:0),dy=(keys.ArrowDown||keys.KeyS?1:0)-(keys.ArrowUp||keys.KeyW?1:0);player.x=Math.max(12,Math.min(W-86,player.x+dx*player.speed*dt));player.y=Math.max(12,Math.min(H-62,player.y+dy*player.speed*dt));if(keys.Space||keys.PointerFire)shoot();shotCd=Math.max(0,shotCd-dt);rapid=Math.max(0,rapid-dt);spread=Math.max(0,spread-dt);player.inv=Math.max(0,player.inv-dt);comboTimer=Math.max(0,comboTimer-dt);if(comboTimer<=0)combo=0;shake=Math.max(0,shake-20*dt);
if(elapsed>=55&&!bossSpawned){spawnEnemy('boss');$('eventStatus').textContent='WARNING • MOERVERSE WARDEN ENTERING SECTOR'}
enemyCd-=dt;if(enemyCd<=0){if(!bossSpawned||bossKilled||Math.random()<.38)spawnEnemy();enemyCd=elapsed<25?.82:elapsed<55?.48:bossKilled?.38:.7}
powerCd-=dt;if(powerCd<=0){spawnPower();powerCd=7+Math.random()*4}
shots.forEach(s=>{s.x+=s.vx*dt;s.y+=s.vy*dt});enemyShots.forEach(s=>{s.x+=s.vx*dt;s.y+=s.vy*dt});powers.forEach(p=>p.x-=p.v*dt);particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.985;p.vy*=.985;p.life-=dt});
for(const s of shots){for(const e of enemies){if(!s.dead&&!e.dead&&hit(s,e,2)){s.dead=true;e.hp-=s.d;if(e.hp<=0)kill(e);break}}}
for(const s of enemyShots){if(!s.dead&&hit(s,player,3)){s.dead=true;damage()}}
for(const p of powers){if(!p.dead&&hit(player,p)){p.dead=true;if(p.type==='shield')lives=Math.min(7,lives+1);else if(p.type==='rapid')rapid=8;else spread=8;burst(p.x+10,p.y+10,8)}}
for(const e of enemies){if(e.dead)continue;if(e.type==='boss'){if(e.x>W-158)e.x-=e.v*dt;e.phase+=dt;e.y=H/2-50+Math.sin(e.phase*1.5)*82}else{e.x-=e.v*dt;e.y+=Math.sin((elapsed+e.phase)*2.1)*(e.type==='mine'?18:7)*dt}e.fire-=dt;if(e.fire<=0&&e.x<W-20){enemyFire(e);e.fire=e.type==='boss'?.72:1.2+Math.random()*1.8}if(hit(player,e,e.type==='boss'?12:5)){if(e.type!=='boss')e.dead=true;damage()}else if(e.x<-150)e.dead=true}
shots=shots.filter(s=>!s.dead&&s.x<W+30&&s.y>-20&&s.y<H+20);enemyShots=enemyShots.filter(s=>!s.dead&&s.x>-30&&s.y>-30&&s.y<H+30);powers=powers.filter(p=>!p.dead&&p.x>-30);enemies=enemies.filter(e=>!e.dead);particles=particles.filter(p=>p.life>0);updateHud(elapsed);if(elapsed>=120)finish(true)}
function drawShip(){ctx.save();if(player.inv>0&&Math.floor(player.inv*12)%2===0)ctx.globalAlpha=.3;if(ship.complete&&ship.naturalWidth){const cx=player.x+32,cy=player.y+23;ctx.translate(cx,cy);ctx.rotate(Math.PI/2);ctx.drawImage(ship,-42,-42,84,84)}else{rect(player.x+4,player.y+18,52,14,'#3153d7');rect(player.x+20,player.y+4,20,38,'#6f91ff');rect(player.x+26,player.y+11,8,15,'#bfeeff')}ctx.restore()}
function drawEnemy(e){const x=e.x,y=e.y;if(e.type==='boss'){rect(x+18,y+8,78,58,'#4b247d');rect(x,y+26,118,30,'#29164f');rect(x+30,y+22,18,18,'#170b27');rect(x+70,y+22,18,18,'#170b27');rect(x+35,y+27,8,8,'#ff4c88');rect(x+75,y+27,8,8,'#5ff5ff');return}if(e.type==='mine'){rect(x+8,y+8,18,18,'#7d3153');rect(x+13,y+13,8,8,'#ff4d78');rect(x+14,y-3,6,8,'#b44564');rect(x+14,y+29,6,8,'#b44564');return}const c=e.type==='interceptor'?'#c3397e':'#e26b44',d=e.type==='interceptor'?'#6d2369':'#923d48';rect(x+5,y+5,e.w-10,8,c);rect(x,y+13,e.w,10,d);rect(x+13,y+10,10,8,'#151225')}
function drawPower(p){const c=p.type==='rapid'?'#54ffd0':p.type==='spread'?'#c078ff':'#5ca5ff';rect(p.x,p.y,20,20,'#101a31');rect(p.x+2,p.y+2,16,16,c);rect(p.x+7,p.y+7,6,6,'#fff')}
function draw(){ctx.save();if(shake>0)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);rect(0,0,W,H,'#020510');stars.forEach(s=>rect(s.x,s.y,s.s,s.s,s.c));ctx.globalAlpha=.23;rect(0,H-86,W,86,'#0b1232');for(let x=0;x<W;x+=16){const h=12+((x*13)%38);rect(x,H-h,12,h,'#111c4c');if(x%64===0)rect(x+3,H-h+5,3,3,'#41d8ff')}ctx.globalAlpha=1;rocks.forEach(r=>{rect(r.x,r.y,r.s,r.s,'#2d3246');if(r.s>9)rect(r.x+3,r.y+3,r.s-6,r.s-6,'#454a61')});drawShip();shots.forEach(s=>rect(s.x,s.y,s.w,s.h,rapid>0?'#64ffd5':spread>0?'#bd7dff':'#63e8ff'));enemyShots.forEach(s=>rect(s.x,s.y,s.w,s.h,s.c));enemies.forEach(drawEnemy);powers.forEach(drawPower);particles.forEach(p=>rect(p.x,p.y,p.s,p.s,p.c));ctx.restore();const b=enemies.find(e=>e.type==='boss'&&!e.dead);if(b){rect(190,12,340,13,'#17112b');rect(194,16,332*(b.hp/b.max),5,'#c64cff')}}
function finish(survived){if(!running)return;running=false;draw();$('eventOverlay').hidden=false;$('eventTitle').textContent=survived&&bossKilled?'EVENT COMPLETE':lives<=0?'SHIP LOST':'EXTRACTION COMPLETE';$('eventText').textContent=`Demo score ${score.toLocaleString()} • ${bossKilled?'Warden defeated':'Warden survived'} • no XP or Passport data saved.`;$('eventStart').textContent='PLAY EVENT AGAIN';$('eventStatus').textContent='DEVELOPER PREVIEW COMPLETE'}
function start(){reset();running=true;$('eventOverlay').hidden=true;$('eventStatus').textContent='FIRST CONTACT • PATROL CONTACT';requestAnimationFrame(loop)}
function loop(t){if(!running)return;const dt=Math.min(.033,(t-last)/1000);last=t;update(dt);draw();if(running)requestAnimationFrame(loop)}
canvas.addEventListener('pointerdown',e=>{keys.PointerFire=true;shoot();e.preventDefault()});window.addEventListener('pointerup',()=>keys.PointerFire=false);window.addEventListener('keydown',e=>{keys[e.code]=true;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault()});window.addEventListener('keyup',e=>keys[e.code]=false);document.querySelectorAll('[data-demo-key]').forEach(b=>{const k=b.dataset.demoKey;b.addEventListener('pointerdown',e=>{e.preventDefault();keys[k]=true});['pointerup','pointercancel','pointerleave'].forEach(ev=>b.addEventListener(ev,()=>keys[k]=false))});$('eventStart').addEventListener('click',start);updateHud(0);draw();
})();